### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by snoopy1412** [eryajf/chatgpt-dingtalk#1]
钉钉提示 ： 消息接收地址校验失败（请确保公网可访问该地址，如无有效SSL证书，可选择禁用证书校验）

**Comment by eryajf** [comment]
你在配置机器人回调接口的步骤，配置的IP是什么呢，需要注意这个IP得是公网IP，包括域名，得是钉钉能回调访问到的才行

**Comment by jaylonluo** [comment]
@eryajf 存在一样的错误 docker日志报错 2022/12/12 02:59:56 unmarshal request body failed: unexpected end of JSON input

**Comment by snoopy1412** [comment]
> 你在配置机器人回调接口的步骤，配置的IP是什么呢，需要注意这个IP得是公网IP，包括域名，得是钉钉能回调访问到的才行


ip配置的是公网的ip,域名也有， docker报错如下
2022/12/12 03:20:59 unmarshal request body failed: unexpected end of JSON input
2022/12/12 03:20:59 request gtp json string : {"model":"text-davinci-003","prompt":"","max_tokens":1024,"temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0}

**Comment by eryajf** [comment]
@jaylonluo @snoopy1412 你俩是不是有点串台了😂，虽然这个项目借鉴了wechatbot，但是配置其实并不一样，注意，config.json的内容应该如下：

```
cat config.json
{
    "api_key": "xxxxxxxxx",
    "session_timeout": 60
}
```

目前我还没有集成更多的配置信息，随后会进行更新。

**Comment by snoopy1412** [comment]
> @jaylonluo @snoopy1412 你俩是不是有点串台了😂，虽然这个项目借鉴了wechatbot，但是配置其实并不一样，注意，config.json的内容应该如下：
> 
> ```
> cat config.json
> {
>     "api_key": "xxxxxxxxx",
>     "session_timeout": 60
> }
> ```
> 
> 目前我还没有集成更多的配置信息，随后会进行更新。

用config.json确实是可行的！
测试的时候，发现chatGPT不能联系上下文回复，不知道是不是个bug,还是有什么操作说明

**Comment by eryajf** [comment]
> 发现chatGPT不能联系上下文回复

的确这块儿还有点问题，随后我看看有没有可能完善这块儿能力

**Comment by eryajf** [comment]
@snoopy1412 最新版本的代码已经修复了这个问题，明天你可以更新到新版本试试。注意新版本配置文件内容有变化。

**Comment by kingmos** [comment]
> 钉钉提示 ： 消息接收地址校验失败（请确保公网可访问该地址，如无有效SSL证书，可选择禁用证书校验）

请问您这个问题解决了吗？我在钉钉开放平台在开发管理页面配置机器人消息接收地址时由于没有https ，报错： 消息接收地址校验失败（请确保公网可访问该地址，如无有效SSL证书，可选择禁用证书校验）

请问在哪里禁用证书校验？

**Comment by eryajf** [comment]
@kingmos 参看这个issue： #44
