### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by lishangyi** [eryajf/chatgpt-dingtalk#101]
![image](https://user-images.githubusercontent.com/56777446/226150297-33e9ca67-e316-4266-ba9f-67721b093728.png)
![image](https://user-images.githubusercontent.com/56777446/226150290-f380f21c-5a90-48b2-9f39-195688ccdd13.png)
大佬想问这个是什么问题和怎么解决?

**Comment by eryajf** [comment]
贴下你的启动命令，需要服务器也开启代理才行，不然现在无法直接请求

**Comment by lishangyi** [comment]
> 

我使用的是新加坡的服务器，使用的是你提供的docker一键部署的命令，是不是不加那个http代理就可以了？

**Comment by lishangyi** [comment]
> 是的，把 http_proxy 留空 就好了

好的谢谢
