### ISSUE TITLE
🗣 征集一个GPT-4的key（暂时不用）

### ISSUE THREAD

**Issue by eryajf** [eryajf/chatgpt-dingtalk#103]
不少人已经用上了gpt-4，也在本项目中发帖希望支持gpt-4，特征集一个gpt-4的key，用于开发测试，一旦用完，可即刻销毁该key。

如有愿意奉献的朋友，请在此帖下边留言。

**Comment by derekxia1988** [comment]
我可以支援一个

**Comment by eryajf** [comment]
> 我可以支援一个

感谢，请通过邮箱与我联系 eryajf@163.com

**Comment by derekxia1988** [comment]
> > 我可以支援一个
> 
> 感谢，请通过邮箱与我联系 [eryajf@163.com](mailto:eryajf@163.com)

实在是抱歉，我好像理解错了，我还没有通过waitlist，单纯的plus是没用的

**Comment by eryajf** [comment]
> 我Plus订阅，官方网页可以GPT-4模型，也可以用accessToken实现gpt-4模型

这个accessToken与api_key应该还是两回事儿吧，咱们这个项目还不支持使用那种方式登陆的能力

**Comment by baby9** [comment]
GPT-4还没有开放API

**Comment by eryajf** [comment]
> GPT-4还没有开放API

好的，那就再等等，有的朋友在issue里直接问gpt-4咋不能用，我还以为可以用了呢

**Comment by neverhoodboy** [comment]
API可以使用GPT-4的，需要提交申请加入waitlist，最近已经陆陆续续有人通过了。

**Comment by Midnight-719** [comment]
> 我Plus订阅，官方网页可以GPT-4模型，也可以用accessToken实现gpt-4模型

这个怎么实现的 指点一下 谢谢
