### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by freefrank** [eryajf/chatgpt-dingtalk#109]
## 问题反馈

- 我觉得应该是我钉钉那边设置有问题，一直会出现回调内容为空。试过旧版机器人和新版企业应用机器人，都是同样的结果。
- 机器人服务器在海外，可以直接访问gpt。

`
chatgpt  | [INFO]2023/03/22 06:55:42 logger.go:21: dingtalk callback parameters: &public.ReceiveMsg{ConversationID:"cidcRSe7j2h0j3RJTgkNhM0f+Dv5wkW1TPERSFtnVCX7jo=", AtUsers:[]struct { DingtalkID string "json:\"dingtalkId\"" }(nil), ChatbotUserID:"$:LWCP_v1:$5s5tBozDH79WS1ExgDHuQRDh+Rw/ogj7", MsgID:"msgzuzXfI42MNvL99oaXmWePg==", SenderNick:"xxx", IsAdmin:true, SenderStaffId:"01213409581040412", SessionWebhookExpiredTime:1679444741543, CreateAt:1679439341268, ConversationType:"1", SenderID:"$:LWCP_v1:$Q1WKtqIjYk5rWMPXxcveyg==", ConversationTitle:"", IsInAtList:false, SessionWebhook:"https://oapi.dingtalk.com/robot/sendBySession?session=xxx", Text:public.Text{Content:"123"}, RobotCode:"dingelkjaywglqypq8h7", Msgtype:"text"}
chatgpt  | [WARNING]2023/03/22 06:55:43 logger.go:33: 从钉钉回调过来的内容为空，根据过往的经验，或许重新创建一下机器人，能解决这个问题
chatgpt  | [WARNING]2023/03/22 06:55:43 logger.go:33: 从钉钉回调过来的内容为空，根据过往的经验，或许重新创建一下机器人，能解决这个问题
chatgpt  | [WARNING]2023/03/22 06:55:43 logger.go:33: 从钉钉回调过来的内容为空，根据过往的经验，或许重新创建一下机器人，能解决这个问题
chatgpt  | [INFO]2023/03/22 06:55:43 logger.go:21: gpt request error: EOF
chatgpt  | [WARNING]2023/03/22 06:55:44 logger.go:33: get gpt result falied: <nil>
`

烦请大佬看一下问题出现在哪里。钉钉那边新版企业应用机器人会有`事件与回调`，但是是AES签名的，好像跟这个机器人无关？

**Comment by eryajf** [comment]
现在签名这块儿不需要做校验也能交互，老出现这个问题，可能是建完机器人得等等，之前也有人出现过，等一等后来好了

**Comment by freefrank** [comment]
我拿node重写了一下后端，好了。。。
