### ISSUE TITLE
context deadline exceeded Error

### ISSUE THREAD

**Issue by cairoHy** [eryajf/chatgpt-dingtalk#11]
[INFO]2022/12/28 11:22:09 logger.go:21: gtp request error: %v 
 Post "https://api.openai.com/v1/completions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[INFO]2022/12/28 11:22:09 logger.go:21: request openai error: %v
 <nil>

**Comment by eryajf** [comment]
网络问题，只能重试
