### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by ihoment-lys** [eryajf/chatgpt-dingtalk#111]
![image](https://user-images.githubusercontent.com/73272214/226822301-6b207c1e-1069-49e4-9f8a-51f2a717f368.png)
回调的时候报错

**Comment by eryajf** [comment]
刚更新了一个新版本，你再尝试下新版本还会不会有这个错误了

**Comment by ihoment-lys** [comment]
![image](https://user-images.githubusercontent.com/73272214/227148667-81f3a2e5-727b-4f88-8c7b-8e7708579bb0.png)
下载了最新的版本，

**Comment by eryajf** [comment]
你配置的模型是哪个

**Comment by ihoment-lys** [comment]
gpt-3.5-turbo
![image](https://user-images.githubusercontent.com/73272214/227150595-b6698fd3-1a2e-41f9-ac10-92fc3d5999fa.png)

**Comment by eryajf** [comment]
你这台主机确认是可以访问 api.openai.com 这个域名的吧，加的代理也是有效的不

**Comment by ihoment-lys** [comment]
服务部署在国外，本地curl 没有问题；怎么验证代理是否有效

**Comment by eryajf** [comment]
如果服务器在国外，把代理的配置留空就可以了

**Comment by ihoment-lys** [comment]
可以了 感谢大神
