### ISSUE TITLE
钉钉机器人配置问题

### ISSUE THREAD

**Issue by kingmos** [eryajf/chatgpt-dingtalk#113]
## 问题反馈
钉钉开放平台在开发管理页面配置机器人消息接收地址时由于没有https ，报错： 消息接收地址校验失败（请确保公网可访问该地址，如无有效SSL证书，可选择禁用证书校验）

请问在哪里禁用证书校验,或者跳过这个限制使用http地址。    

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

**Comment by eryajf** [comment]
看  #44
