### ISSUE TITLE
🙋 能否将API Key改成access token?主要是余额用得太快了，网页版似乎不消耗余额。

### ISSUE THREAD

**Issue by luwa1107** [eryajf/chatgpt-dingtalk#118]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

**Comment by zanderzhng** [comment]
access_token 有个刷新机制，很麻烦。

**Comment by eryajf** [comment]
> access_token 有个刷新机制，很麻烦。

对于服务端来说，其实更难的是要使用无头浏览器模拟整个登陆流程，而且现在官方越来越多的检测是否为真人，再加上网络因素影响，就让这个事儿难度再次加倍，所以这个功能目前不会考虑了
