### ISSUE TITLE
用付费版的api key，启动容器会报错

### ISSUE THREAD

**Issue by PIRANHACHAN** [eryajf/chatgpt-dingtalk#119]
服务器是德国的
用免费版的key，正常跑

yaml配置
![image](https://user-images.githubusercontent.com/24191934/227402123-3bf39b4c-db7b-41d0-a7d9-6b0450c0b6d0.png)

报错内容
```panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/app/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/app/public/public.go:20 +0xea
main.init.0()
	/app/main.go:15 +0x17
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/app/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/app/public/public.go:20 +0xea
main.init.0()
	/app/main.go:15 +0x17
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/app/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/app/public/public.go:20 +0xea
main.init.0()
	/app/main.go:15 +0x17
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/app/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/app/public/public.go:20 +0xea
main.init.0()
	/app/main.go:15 +0x17
```

**Comment by eryajf** [comment]
在服务器请求一下看看是否通。

```sh
curl 'https://api.openai.com'
```

**Comment by eryajf** [comment]
好像还有个原因，付费版的能够通过web正常使用，但是api还是需要通过白名单审核才行，所以你的token反而无法正常使用。
你可以找一个免费账号的key再填进去试试

**Comment by PIRANHACHAN** [comment]
> 在服务器请求一下看看是否通。
> 
> ```shell
> curl 'https://api.openai.com'
> ```

![image](https://user-images.githubusercontent.com/24191934/227410735-0be548ec-594e-4aa2-b4cf-83398570c544.png)

服务器应该是没问题的，我用免费key是可以正常启动容器，日志没报错，机器人也正常回复

**Comment by PIRANHACHAN** [comment]
> 好像还有个原因，付费版的能够通过web正常使用，但是api还是需要通过白名单审核才行，所以你的token反而无法正常使用。 你可以找一个免费账号的key再填进去试试

充了钱成为“尊贵”VIP反而还无法使用了，找文档也没看到哪里有说明可以申请什么白名单，非常迷惑

**Comment by eryajf** [comment]
那看来就是第二个原因了。
这个正常，主要是现在官方在卡最新版gpt-4的模型使用，所以搞了个白名单的机制，你可以在官网找下入口，具体我也不知道链接是多少了

**Comment by PIRANHACHAN** [comment]
> 那看来就是第二个原因了。 这个正常，主要是现在官方在卡最新版gpt-4的模型使用，所以搞了个白名单的机制，你可以在官网找下入口，具体我也不知道链接是多少了

我把yaml配置改了一下
![image](https://user-images.githubusercontent.com/24191934/227413624-d58c3d10-5b6c-4f27-9e9e-7683e98e47f6.png)

那么，容器报错变成了：
```
023/03/24 11:00:38.227125 ERROR RESTY Get "https://api.openai.com/dashboard/billing/credit_grants": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
2023/03/24 11:00:50.234406 ERROR RESTY Get "https://api.openai.com/dashboard/billing/credit_grants": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 2
2023/03/24 11:01:02.244658 ERROR RESTY Get "https://api.openai.com/dashboard/billing/credit_grants": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 3
2023/03/24 11:01:14.251863 ERROR RESTY Get "https://api.openai.com/dashboard/billing/credit_grants": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 4
2023/03/24 11:01:14.251924 runner.go:231: [I] The HTTP Server is running on :8090
```

可以启动容器，并能接收到机器人的消息了。但是依然无法响应回复。
我好奇的是，即使我的付费key是因为某些原因不可用，但这也会直接导致容器无法启动吗？

**Comment by eryajf** [comment]
你服务器在国外，那么http_proxy的配置项应该留空

**Comment by hustwy** [comment]
这里申请4API的白名单https://openai.com/waitlist/gpt-4-api

**Comment by PIRANHACHAN** [comment]
> 这里申请4API的白名单https://openai.com/waitlist/gpt-4-api

我已经可以用gpt-4-api

**Comment by eryajf** [comment]
> > 这里申请4API的白名单[openai.com/waitlist/gpt-4-api](https://openai.com/waitlist/gpt-4-api)
> 
> 我已经可以用gpt-4-api

对gpt-4的兼容的确没有做过测试，你这边是否愿意分享下你的key，我做下测试，做完之后，你把key重置就好了

**Comment by eryajf** [comment]
> > > > 这里申请4API的白名单[openai.com/waitlist/gpt-4-api](https://openai.com/waitlist/gpt-4-api)
> > > 
> > > 
> > > 我已经可以用gpt-4-api
> > 
> > 
> > 对gpt-4的兼容的确没有做过测试，你这边是否愿意分享下你的key，我做下测试，做完之后，你把key重置就好了
> 
> 可以，但我不知道怎么发给你

通过邮箱联系我：eryajf@163.com
