### ISSUE TITLE
如何通过api的方式去调用 网页版的gpt

### ISSUE THREAD

**Issue by huaxulong** [eryajf/chatgpt-dingtalk#12]
model:text-davinci-003 这个模型感觉比网页版的gpt 的智能化差的很远呢？ 有没有办法通过api的方式去调用 网页版的gpt

**Comment by eryajf** [comment]
没有太好的方案目前

**Comment by XueMeijing** [comment]
可以看下这个谷歌扩展？应该主要是处理下http流 https://github1s.com/wong2/chat-gpt-google-extension/blob/HEAD/src/background/index.ts

**Comment by wensonsmith** [comment]
现在这个接口和网页版差太多了，用起来意义不大

**Comment by wensonsmith** [comment]
> 可以看下这个谷歌扩展？应该主要是处理下http流 https://github1s.com/wong2/chat-gpt-google-extension/blob/HEAD/src/background/index.ts

这个运行在浏览器中，可以直接使用浏览器的环境，在服务器中需要模拟浏览器。比这个要难多了

**Comment by XueMeijing** [comment]
> > 可以看下这个谷歌扩展？应该主要是处理下http流 https://github1s.com/wong2/chat-gpt-google-extension/blob/HEAD/src/background/index.ts
> 
> 这个运行在浏览器中，可以直接使用浏览器的环境，在服务器中需要模拟浏览器。比这个要难多了

确实，我最近也找了很多库，目前发现这个人的python 和nodeJs库是可以的比较简单，不知道他怎么破解的。可以用socket走他的代理服务器 https://github.com/PawanOsman/PyGPT

**Comment by eryajf** [comment]
期待有精力的朋友PR补充这块儿的能力，我最近没有太多精力完善

**Comment by wensonsmith** [comment]
等等吧，很快就要出 chatgpt 模型的接口了

**Comment by XueMeijing** [comment]
> 

不会go，做了一个python版本的钉钉机器人可以参考下 https://github.com/XueMeijing/dingtalk-chatgpt-bot
