### ISSUE TITLE
可否添加在windows服务器下的部署方式

### ISSUE THREAD

**Issue by MeditatorV** [eryajf/chatgpt-dingtalk#120]
因为本人使用的是windows的轻量云，无法使用docker，可否添加在windows服务器下的部署方式说明

**Comment by eryajf** [comment]
参照README当中，使用二进制部署的方案进行部署就可以了。

如果你想通过命令行直接部署，可以直接下载release中的[压缩包](https://github.com/eryajf/chatgpt-dingtalk/releases) ，请根据自己系统以及架构选择合适的压缩包，下载之后直接解压运行。

下载之后，在本地解压，即可看到可执行程序，与配置文件：

```sh
$ tar xf chatgpt-dingtalk-v0.0.4-darwin-arm64.tar.gz
$ cd chatgpt-dingtalk-v0.0.4-darwin-arm64
$ cp config.dev.json  config.json # 然后根据情况调整配置文件内容
$ ./chatgpt-dingtalk  # 直接运行

# 如果要守护在后台运行
$ nohup ./chatgpt-dingtalk &> run.log &
$ tail -f run.log
```

**Comment by MeditatorV** [comment]
谢谢
