### ISSUE TITLE
调用账单的接口应该没有使用config里的URL

### ISSUE THREAD

**Issue by MeditatorV** [eryajf/chatgpt-dingtalk#121]
我使用了腾讯云的云函数部署了openai的接口代理，在config.json里填入的是代理的url，但启动时调用的是api.openai.com的url
![image](https://user-images.githubusercontent.com/47035563/227455384-4450beaa-5be1-42a9-a043-a74e03828cd7.png)

**Comment by eryajf** [comment]
确实如此，这是个bug，你有兴趣提交个PR解决这个问题吗

**Comment by MeditatorV** [comment]
感谢您的邀请，因为我不是开发人员，只会使用，没有相关的能力解决这问题，另，建议服务的端口不要改死8090，因为有可能此端口有可能被使用。建议在config.json里可对服务的配置。，我正使用的是windows的发布版

**Comment by eryajf** [comment]
OK，晚点我会把这两个功能一并支持了
