### ISSUE TITLE
Sorry, Page Not Found

### ISSUE THREAD

**Issue by qingshuicn** [eryajf/chatgpt-dingtalk#124]
使用dokcer 和二进制部署，访问都是Not Found 是哪里出了问题，服务器在国外的

**Comment by eryajf** [comment]
给一些明细，比如你部署的启动命令。

以及这个not found是哪里报的。最好给下docker的服务日志

**Comment by qingshuicn** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/32059631/227517398-7cf734da-da65-4458-a0c0-3ed4b5ebffe7.png">

部署启动的命令是直接复制的
docker run -itd --name chatgpt -p 8090:8090  -v `pwd`/config.json:/app/config.json --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest

config 存放在 /root/dingtalk/config.json


`{
    "api_key": "sk-De3DbyO0lQNSPQHIReElbkFJk1Bg2IsKNDJLYqYjk7nE",
    "base_url": "",
    "model": "gpt-3.5-turbo",
    "session_timeout": 600,
    "http_proxy": "",
    "default_mode": "单聊",
    "max_request": 0,
    "service_url": "http://xyw.t-tech.cn"
}`

**Comment by eryajf** [comment]
@qingshuicn 刚刚你这条消息key泄露了，我先把消息删了，你最好也重试下key

我已经看到了，如果部署没有问题，那么你直接配置钉钉的回调就可以了，这个接口是个post接口，所以直接在浏览器访问会报这个内容，这是正常现象。

**Comment by qingshuicn** [comment]
key,我是删除了一些字符的，我在钉钉回调，没消息回复，钉钉我看没有其他需要配置的

**Comment by eryajf** [comment]
消息没有回复，那docker这边的日志输出了什么

**Comment by qingshuicn** [comment]
搞定了，但是现在碰到另外一个问题
“请求openai失败了，错误信息：maximum text length exceeded，看起来是超过最大对话限制了，已自动重置您的对话

我并没有限制请求次数

**Comment by eryajf** [comment]
这个错误是正常的，这是官方对api接口的最大请求限制，是4096，超过这个之后，就只能重新对话，所以后台就默认把session重置了

**Comment by qingshuicn** [comment]
主要是才来会不超过10次对话就不行了，这个很蛋疼
