### ISSUE TITLE
消息调回地址出问题（已将之前的issues都看过一遍）

### ISSUE THREAD

**Issue by fengshuiyu** [eryajf/chatgpt-dingtalk#125]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**
请问按照j将http改成https，将跳出来的ssl证书校验禁用之后，再次换回http，此时还是出现校验出错，再改成https，发现ssl证书认证又改回了启用，这种情况该怎么办？

**Comment by eryajf** [comment]
这两天有几个新朋友遇到这个问题，等我下午空了，我再走下流程试试：https://github.com/eryajf/chatgpt-dingtalk/issues/44#issuecomment-1483113294

**Comment by arthurain** [comment]
@eryajf 钉钉一直显示ssl校验失败这个问题，连着失败了一天后，今天莫名其妙地又成功了，貌似是钉钉那边的问题，实在找不到规律。现在机器人已经部署成功，但是返回图片有问题，一直都是感叹号。是不是要返回图片的功能的话，service_url这个环境变量一定要填呢？我现在是放空的没有填

**Comment by eryajf** [comment]
> @eryajf 钉钉一直显示ssl校验失败这个问题，连着失败了一天后，今天莫名其妙地又成功了，貌似是钉钉那边的问题，实在找不到规律。现在机器人已经部署成功，但是返回图片有问题，一直都是感叹号。是不是要返回图片的功能的话，service_url这个环境变量一定要填呢？我现在是放空的没有填

好吧，原本我打算再走下这个流程看看是不是有啥变化的，看起来这块儿目前还是有点玄学。


对，必须填，否则图片是加载不到的

**Comment by arthurain** [comment]
> > @eryajf 钉钉一直显示ssl校验失败这个问题，连着失败了一天后，今天莫名其妙地又成功了，貌似是钉钉那边的问题，实在找不到规律。现在机器人已经部署成功，但是返回图片有问题，一直都是感叹号。是不是要返回图片的功能的话，service_url这个环境变量一定要填呢？我现在是放空的没有填
> 
> 
> 
> 好吧，原本我打算再走下这个流程看看是不是有啥变化的，看起来这块儿目前还是有点玄学。
> 
> 
> 
> 
> 
> 对，必须填，否则图片是加载不到的

原来如此，感谢感谢。填写就是填我服务器的地址对吧？这个参数是不是没办法在对话中设置，必须在部署时设置呢？

**Comment by eryajf** [comment]
对，部署时候配置。填写的是你钉钉配置回调的那个地址
