### ISSUE TITLE
🙋 问题文字太长 会报错question length exceeded

### ISSUE THREAD

**Issue by liwux** [eryajf/chatgpt-dingtalk#129]
## 问题反馈
[INFO]2023/03/25 22:25:39 logger.go:21: gpt request error: maximum question length exceeded
[WARNING]2023/03/25 22:25:40 logger.go:33: get gpt result falied: <nil>

**Comment by eryajf** [comment]
一个独立上下文的对话长度有限，这是官方接口的限制，发重置标签就可以了。
