### ISSUE TITLE
从1.0.3 升级到1.0.5 发现不能用了

### ISSUE THREAD

**Issue by aleonchen** [eryajf/chatgpt-dingtalk#130]
采用了docker-compose的模式，升级到1.0.5之后，考虑到本身都是docker，而且可以直接外网访问，新的参数BASE_URL: "" 和 HTTP_PROXY: ""，都配置为空。但是这样配置后，就一直机器人都没反应了。访问服务返回"Not Found"，log里面也没有错误显示，不知道可以如何调试？

**Comment by eryajf** [comment]
你的服务器是在境外吗，机器人没反应是指怎么个没反应呢？

**Comment by eryajf** [comment]
> 在境外，没反应是不会有任何的响应，docker log里面也没有任何输出

可以手动curl一下试试，没反应有一种可能是，服务是正常的，而问题出在钉钉后台那里，获取你重建一下机器人应该就好了
