### ISSUE TITLE
请问docker镜像同步更新了吗

### ISSUE THREAD

**Issue by Facemax** [eryajf/chatgpt-dingtalk#133]
## 问题反馈
请问docker镜像同步更新了吗，我stop和remove了原来镜像，然后通过指令
docker run -itd --name chatgpt -p 8090:8090 --add-host="host.docker.internal:host-gateway" -e APIKEY=xx -e BASE_URL="" -e MODEL="gpt-3.5-turbo" -e SESSION_TIMEOUT=300 -e HTTP_PROXY="" -e DEFAULT_MODE="单聊" -e MAX_REQUEST=0 -e PORT=8090 -e SERVICE_URL="xx" --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest
布置成功，
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/19884263/227877925-b788f969-f5bf-4d9a-a950-96e3231b3609.png">
但是，帮助没有模版功能，#图片也无法使用
![image](https://user-images.githubusercontent.com/19884263/227877798-f457da79-a43b-4009-aee1-43a8761374e0.png)

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

**Comment by eryajf** [comment]
部署命令对的。

你说的本地开发模式布置是指什么，没理解

**Comment by Facemax** [comment]
> 部署命令对的。
> 
> 你说的本地开发模式布置是指什么，没理解
是这个本地开发，我能基于你的程序进行接口参数调整？不限于配置文件
# 获取项目
$ git clone https://github.com/eryajf/chatgpt-dingtalk.git

# 进入项目目录
$ cd chatgpt-dingtalk

# 复制配置文件，根据个人实际情况进行配置
$ cp config.dev.json config.json

# 启动项目
$ go run main.go

**Comment by eryajf** [comment]
对，这样就可以启动，然后进行开发调试了
