### ISSUE TITLE
1.0.5版本生成图片后，钉钉聊天界面发送为空图片

### ISSUE THREAD

**Issue by wangweinwu** [eryajf/chatgpt-dingtalk#134]
1. 单聊或在群组中使用#图片 生成图片，机器人发送消息中，内容为空白图片：
<img width="364" alt="image" src="https://user-images.githubusercontent.com/18113117/227885042-24f93312-f66e-4657-b99c-5165f8692b67.png">
2. 登录服务器查看images目录，有正常图片生成，且打开显示内容正常.

```
-rw-r--r-- 1 root root 1722668 Mar 27 16:18 20230327-161847.png
-rw-r--r-- 1 root root 1793557 Mar 27 16:14 20230327-161413.png
```

**Comment by eryajf** [comment]
service_url 没有正确配置

**Comment by wangweinwu** [comment]
service_url的定义是服务可访问的地址，这个是仅需要解析到当前服务的ip就可以，还是需要搭建页面服务？能否直接配置ip

**Comment by eryajf** [comment]
就是你钉钉后台配置回调的那个地址，一模一样就可以

**Comment by wangweinwu** [comment]
配置成http://[ip]:[port]的样式，已经可以正常处理。
