### ISSUE TITLE
二进制相关的部署方式能讲解一下吗，我控制台没有任何错误输出，但是@机器人没有什么反应

### ISSUE THREAD

**Issue by XYJ-1** [eryajf/chatgpt-dingtalk#135]
## 问题反馈
2023/03/28 11:32:18.624572 ERROR RESTY Get "/api.openai.com/dashboard/billing/credit_grants": unsupported protocol scheme "", Attempt 1
2023/03/28 11:32:20.636547 ERROR RESTY Get "/api.openai.com/dashboard/billing/credit_grants": unsupported protocol scheme "", Attempt 2
2023/03/28 11:32:22.650734 ERROR RESTY Get "/api.openai.com/dashboard/billing/credit_grants": unsupported protocol scheme "", Attempt 3
2023/03/28 11:32:24.652285 ERROR RESTY Get "/api.openai.com/dashboard/billing/credit_grants": unsupported protocol scheme "", Attempt 4
2023/03/28 11:32:24.652418 runner.go:231: [I] The HTTP Server is running on :8090

**Comment by XYJ-1** [comment]
@eryajf

**Comment by eryajf** [comment]
看下你的配置文件
然后服务启动之后，你先用readme的curl验证下服务



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月28日 14:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [eryajf/chatgpt-dingtalk] 二进制相关的部署方式能讲解一下吗，我控制台没有任何错误输出，但是@机器人没有什么反应 (Issue #135) |

@eryajf

**Comment by XYJ-1** [comment]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/103086730/228214615-53323ca0-80d2-4ab8-9fe4-59fece207a50.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/103086730/228214831-5eb52ba3-a88e-4a8f-97eb-8e2d66e83571.png">

像我这样开在本地，没有部署到服务器上的话，是不是无法运行，好像

**Comment by XYJ-1** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/103086730/228215050-8abb9dcc-7a2b-4eda-83a0-f6f7bd57f1fe.png">
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/103086730/228215097-7b1a438d-01a0-49ef-bd34-e9aef68aacc1.png">

像我这样开在本地，没有部署到服务器上的话，是不是无法运行，好像

**Comment by eryajf** [comment]
是的，不行，不过有一个两种方案，一种是不通过钉钉调试，直接通过接口调试，另一种是利用[frp](https://github.com/fatedier/frp)来做，我本地调试的时候就是用的这种方案。

也推荐你使用这种方案，配置简单，使用方便。

**Comment by XYJ-1** [comment]
好吧，感谢博主
