### ISSUE TITLE
服务器在国外，钉钉后台应用创建好了之后在群里@机器人之后报错

### ISSUE THREAD

**Issue by asmenglei** [eryajf/chatgpt-dingtalk#147]
服务器在国外，在服务器上使用的文档中的二进制部署
![image](https://user-images.githubusercontent.com/7092966/228996355-9906f404-e22b-4f7f-8b78-0151c3bf8d3e.png)

INFO [after generate prompt: "成都天气"]
INFO [gpt request error: Post "api.openai.com/v1/chat/completions": unsupported protocol scheme ""]
WARN [get gpt result falied: <nil>]

报错信息如下
![image](https://user-images.githubusercontent.com/7092966/228995981-44992d74-f4cd-4665-bf9e-7664af59a298.png)

config.json 配置内容如下
![image](https://user-images.githubusercontent.com/7092966/228996490-f025a602-29b8-458d-9e01-9e1c75758d09.png)

能帮看下这个是什么问题么？万分感激

**Comment by eryajf** [comment]
把 base_url 留空然后重启服务

**Comment by asmenglei** [comment]
![image](https://user-images.githubusercontent.com/7092966/229017588-36f0b8b9-3700-4c68-8b60-867ab9a60bb0.png)
base_url 留空就报上图的错误

**Comment by asmenglei** [comment]
请大神帮看下上面这个问题，辛苦啦 @eryajf

**Comment by eryajf** [comment]
你这个服务器无法成功访问 api.openai.com 这个域名，你需要解决的是这个问题

**Comment by asmenglei** [comment]
部署代码的服务器可以访问这个域名啊
![image](https://user-images.githubusercontent.com/7092966/229058814-bcafb5ff-7daf-4192-a21c-094806b02265.png)

**Comment by eryajf** [comment]
你拉的代码是最新的不

**Comment by asmenglei** [comment]
是最新的啊

![image](https://user-images.githubusercontent.com/7092966/229065526-22eb7991-9c17-49f4-8476-ff3941168c51.png)

**Comment by asmenglei** [comment]
这个同学也遇到这个问题了
![image](https://user-images.githubusercontent.com/7092966/229066195-32e419a0-79b5-4402-8434-b0b8dbdb8a19.png)

**Comment by asmenglei** [comment]
@eryajf 大神帮忙看下这个问题呢？刚才使用 二进制部署  使用同样的 config.json 还是同样的报错。。
![image](https://user-images.githubusercontent.com/7092966/229081330-0054b847-cbdc-4885-9527-709efd124cb8.png)

**Comment by asmenglei** [comment]
更换了 另外一台在国外的 服务器。同样的报错呢。，大神帮看看吧 @eryajf

**Comment by eryajf** [comment]
你这边给到的信息我始终无法正确get到，与我邮件联系吧

**Comment by asmenglei** [comment]
> 你这边给到的信息我始终无法正确get到，与我邮件联系吧

好的，已发送邮件，请查收 ，谢谢
