### ISSUE TITLE
怎么查看日志呀？

### ISSUE THREAD

**Issue by luxizi** [eryajf/chatgpt-dingtalk#15]
![image](https://user-images.githubusercontent.com/48914886/217149482-ebd1e151-7f08-4703-9c95-d418328e6f19.png)

**Comment by eryajf** [comment]
这个一般就是请求失败了，现在通过接口请求chatGPT越来越不稳定了，有点随缘。如果你是docker部署的，可以docker logs -f chatgpt-dingtalk 来查看日志。
