### ISSUE TITLE
🙋 有无办法限制某些人或群添加企业内部机器人

### ISSUE THREAD

**Issue by goxofy** [eryajf/chatgpt-dingtalk#157]
公司两万多人，群也有几千个，企业内部机器人怎么管理比较好呢？

**Comment by eryajf** [comment]
很快相关功能就会上线

**Comment by goxofy** [comment]
大佬牛逼！

**Comment by goxofy** [comment]
@eryajf 大佬，请教一下allowed user和group，user是写手机号吗？group是直接写群名称？

**Comment by eryajf** [comment]
不是手机号，一个是群名称，一个是人的名字。



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月02日 22:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [eryajf/chatgpt-dingtalk] 🙋 有无办法限制某些人或群添加企业内部机器人 (Issue #157) |

@eryajf 大佬，请教一下allowed user和group，user是写手机号吗？group是直接写群名称？

**Comment by goxofy** [comment]
@eryajf  明白了，谢谢！
