### ISSUE TITLE
抱歉，您不在该机器人对话功能的白名单当中！ 

### ISSUE THREAD

**Issue by alex-chan** [eryajf/chatgpt-dingtalk#161]
更新了最近的repo钉钉老弹这个问题

allow配置都填了空字符串

**Comment by eryajf** [comment]
你是用什么方式启动的，能否看下启动命令，以及配置信息，我这边实测全部留空不会走到这个逻辑里

**Comment by eryajf** [comment]
刚刚发了一版，修复了几个问题，你可以拉取最新版本试试，不过如果还有错误，请带上相关信息

**Comment by arthurain** [comment]
> 刚刚发了一版，修复了几个问题，你可以拉取最新版本试试，不过如果还有错误，请带上相关信息

我也遇到这个问题了，刚刚才拉的新版本。命令为docker run -itd --name chatgpt -p 80:8090 -v ./data:/app/data --add-host="host.docker.internal:host-gateway" -e APIKEY=mykey -e BASE_URL="" -e MODEL="gpt-3.5-turbo" -e SESSION_TIMEOUT=600 -e HTTP_PROXY="" -e DEFAULT_MODE="串聊" -e MAX_REQUEST=0 -e PORT=8090 -e SERVICE_URL="myurl" -e CHAT_TYPE="0" -e ALLOW_GROUPS="" -e ALLOW_USERS="" -e ADMIN_USERS="" --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest

**Comment by eryajf** [comment]
> > 刚刚发了一版，修复了几个问题，你可以拉取最新版本试试，不过如果还有错误，请带上相关信息
> 
> 我也遇到这个问题了，刚刚才拉的新版本。命令为docker run -itd --name chatgpt -p 80:8090 -v ./data:/app/data --add-host="host.docker.internal:host-gateway" -e APIKEY=mykey -e BASE_URL="" -e MODEL="gpt-3.5-turbo" -e SESSION_TIMEOUT=600 -e HTTP_PROXY="" -e DEFAULT_MODE="串聊" -e MAX_REQUEST=0 -e PORT=8090 -e SERVICE_URL="myurl" -e CHAT_TYPE="0" -e ALLOW_GROUPS="" -e ALLOW_USERS="" -e ADMIN_USERS="" --restart=always dockerproxy.com/eryajf/chatgpt-dingtalk:latest

再拉取最新镜像试下
