### ISSUE TITLE
您不在该机器人对话功能的白名单当中

### ISSUE THREAD

**Issue by Timoshao** [eryajf/chatgpt-dingtalk#164]
## 问题反馈

最新版的镜像 报错
![image](https://user-images.githubusercontent.com/108260847/229404613-e04cfba7-411f-45d4-a591-45fcf2c20d2c.png)

![image](https://user-images.githubusercontent.com/108260847/229404541-de97f023-1a31-47ca-9303-487cc5a61e93.png)

**Comment by eryajf** [comment]
这个环境变量是通过在线的docker查看的吗，另外，看下你的镜像时间，是不是最新的

**Comment by Timoshao** [comment]
> 这个环境变量是通过在线的docker查看的吗，另外，看下你的镜像时间，是不是最新的
可以了 重新拉取了镜像正常了
