### ISSUE TITLE
怎么更换openai的api_key

### ISSUE THREAD

**Issue by leoxupro** [eryajf/chatgpt-dingtalk#187]
怎么更换openai的api_key，dingtalk已经运行正常，需要更换key

**Comment by WinMin** [comment]
> 怎么更换openai的api_key，dingtalk已经运行正常，需要更换key

https://github.com/eryajf/chatgpt-dingtalk#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E
