### ISSUE TITLE
日志报 ssl证书过期

### ISSUE THREAD

**Issue by starpipi** [eryajf/chatgpt-dingtalk#20]
通过curl模拟钉钉推过来的消息测试连通性。
日志显示请求openai的api的ssl证书过期。实际官方证书确实没过期。

本地使用curl访问也提示过期。
尝试将openai的证书下载并添加到机器的 /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem后
curl已经不提示过期。

但是在go中请求仍旧提示ssl证书过期。

没写过go，请问有办法忽略ssl证书吗？或者有什么地方能够配置？
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/3281064/217978398-1626c115-7633-48b5-93a6-2dcf0f2f225e.png">
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/3281064/217978462-9e03770f-bc07-4b27-8128-57ea50edf3ce.png">
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/3281064/217978504-59023259-2430-4e13-be88-935d9de19621.png">

**Comment by starpipi** [comment]
暂时用docker跑了 规避掉此问题

**Comment by eryajf** [comment]
添加了ssl的忽略，稍后你可以验证下[最新版本](https://github.com/eryajf/chatgpt-dingtalk/releases/tag/v0.0.8)

见： #22
