### ISSUE TITLE
这个提示是不是正常的？

### ISSUE THREAD

**Issue by luker2013** [eryajf/chatgpt-dingtalk#23]
`[INFO]2023/02/10 04:24:37 logger.go:21: gtp request error: %v 
 Post "https://api.openai.com/v1/completions": dial tcp: lookup api.openai.com on 183.60.82.98:53: read udp 172.17.0.2:52575->183.60.82.98:53: i/o timeout`

**Comment by luker2013** [comment]
是否需要科学上网方式才能使用？

**Comment by eryajf** [comment]
你是在本地运行的吗，我这边用的阿里云的服务器，实测下来还算稳定。科学上网之后，肯定速度更好一些

**Comment by luker2013** [comment]
我在腾讯云服务器上部署的，docker方式安装。

**Comment by luker2013** [comment]
单独curl请求https://api.openai.com/v1/completions是可以访问，如果参数正确也是能得到结果的。
但如果通过本项目8090去请求，就会提示超时，很奇怪。

**Comment by luker2013** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/6269043/218004881-2926aebc-f7bf-49c1-a6b0-333fc55b524d.png">

**Comment by eryajf** [comment]
我这边解析出来的IP是：52.152.96.252，你可以绑定下hosts，然后重试下

**Comment by luker2013** [comment]
这是cdn吧，每次解析都不一样，关键是单独请求都可以发送，不会超时。

**Comment by luker2013** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6269043/218053546-938c235c-1e80-490c-9853-35eebe98ab8f.png">
每次提交都会把上一次的问题和答案一起拼接提交，是故意这么设计的么？有什么好处？

**Comment by eryajf** [comment]
这样能有一个连续对话的能力，不过貌似也不是很强，你给他发一个 清空会话 它就会清空这个上下文了。后续我看看把这个抽成配置项
