### ISSUE TITLE
Docker拉下来的镜像用的不是chatgpt的接口吗?

### ISSUE THREAD

**Issue by DragonGo** [eryajf/chatgpt-dingtalk#25]
如图
![image](https://user-images.githubusercontent.com/22055256/218022988-924e9890-a737-42f8-bcb7-c1ad96b04cdf.png)

**Comment by eryajf** [comment]
只要拉的是这个镜像，应该不会

话说你问的问题是什么，我这边也尝试一下呢

**Comment by DragonGo** [comment]
> 
我问它
”你属于什么公司，谁投资你的“

而且它的回答和网站上面问回答的有点不一样

**Comment by eryajf** [comment]
这个使用的是[gpt-3](https://platform.openai.com/docs/models/gpt-3)这个模型，确实不能跟网页版的对比，网页版是最新的，我这边也会持续关注，如果有新的，会跟进更新
