### ISSUE TITLE
这会儿也不是高峰期，一直说机器人太累了。。。

### ISSUE THREAD

**Issue by s0ng1** [eryajf/chatgpt-dingtalk#27]
![image](https://user-images.githubusercontent.com/101986150/218045996-17824dfa-ce3a-46a4-87db-208eef3f3888.png)

**Comment by s0ng1** [comment]
![image](https://user-images.githubusercontent.com/101986150/218046401-a67a6b5d-9cbf-4b5b-9891-b22e6658f8d0.png)

**Comment by eryajf** [comment]
你配置的session_timeout是多少呢，建议给大一点，应该能有一些缓解

**Comment by s0ng1** [comment]
> 你配置的session_timeout是多少呢，建议给大一点，应该能有一些缓解

没看那个，配置的是180，您那儿建议配置多少呢？

**Comment by eryajf** [comment]
按说180已经不算少了，你是通过docker部署的吗，使用的是最新版本的镜像吗，最新版本加了重试机制，默认会重试两次，成功率会增加不少

**Comment by eryajf** [comment]
你刚刚截图有点少，你从日志里看到请求重试了没有。

确实这个版本还不行，只能玩一玩。

**Comment by s0ng1** [comment]
> 你刚刚截图有点少，你从日志里看到请求重试了没有。
> 
> 确实这个版本还不行，只能玩一玩。

我看了，重试了两次。根chatgpt查的不是一点半点的

**Comment by eryajf** [comment]
重试了两次还经常失败，应该是你那边服务器客户端网络的因素比较大，我这边现在这种情况出现的比较少了。网页版的代表最先进的模型与能力，这个确实没法比，我也在持续关注中
