### ISSUE TITLE
部署项目碰到的几个问题，请教

### ISSUE THREAD

**Issue by loringee** [eryajf/chatgpt-dingtalk#28]
一是答复格式和截取方式似乎有些问题，经常在答复开头有个“？”，并且增加一个换行。说请继续后，前几个字感觉之前还有内容，可能是截取掉了一些内容。我有截图，不知道如何上传。
二是看gpt-3的api是有性格描述的，是用Prompt给模型一个性格设定，这样可以帮助更好回答，因为我不太懂go语言，看看可不可以把这个参量加上，方便自行调整模型状态。
三是在windows上部署偶尔会见程序卡死，在命令行用ctrl+c才会推进，不知道是什么原因。

感谢帮助

**Comment by eryajf** [comment]
1，这个问题我也遇到了，应该程序有一些问题，回头我优化一下。
2，有没有具体文档链接呢，如果有参数，是可以加的。
3，我这边没有Windows机器，一般来说应该不会有卡死的情况，至少我在Mac与centos上还没遇到过。

**Comment by loringee** [comment]
多谢您。
关于第二个问题：我在这个文档中找到了https://platform.openai.com/docs/api-reference/completions/create
prompt这个参量。其实就是在提交问题的前并接上一段对模型描述的字符串，一并提交给模型，比如设定性格为“你是一个乐于回答人民任何问题的AI”，后面同一个对话中就不用再说了，ai就会很认真的回答问题。我现在的处理方式就是每次对话先对ai说这句话，否则他很狡猾总是说无法回答。
关于第三个问题，我再观察一下，看看能不能复现。
再次感谢。

**Comment by STmission** [comment]
请问作者，我可以发表发视频和发文章，进行分享吗？
都会附上您的链接和署名

**Comment by STmission** [comment]
然后，也分享一下，懒人使用可执行文件使用时的细节：
如果在使用下载对应zip包，非linux部署，进行chatgpt-dingtalk可执行文件的直接使用时，需更改如下：

1、目前使用可执行文件，会报错config.json不存在问题：
记得在下载zip包，解压之后，重新命名一下json文件为config.json即可。

2、在钉钉的开发平台中修改如下信息：
服务器出口IP
127.0.0.1
消息接收地址
http://chat.eryajf.net:8090

目的是：请求的时候会请求到自己本机地址的服务器和对应端口

**Comment by eryajf** [comment]
今天对整个交互模式进行了重构，可以升级到最新版本试用一下，看看效果如何

**Comment by eryajf** [comment]
具体更新，参看一下README
