### ISSUE TITLE
由于系统维护，@能力暂不可用，由此带来的不便非常抱歉

### ISSUE THREAD

**Issue by carto1111** [eryajf/chatgpt-dingtalk#29]
钉钉机器人最近都不能用了，提示：由于系统维护，@能力暂不可用，由此带来的不便非常抱歉，你们不会吗

**Comment by eryajf** [comment]
我这里没有遇到这样的情况，你的钉钉机器人是最近新建的吗，尝试重建一下试试呢

**Comment by carto1111** [comment]
好的，我试试，不是新建的，建了很久的，之前是正常的。我重新建一个看看


二丫讲梵 ***@***.***> 于 2023年2月11日周六 10:38写道：

**Comment by carto1111** [comment]
新建的可以，问题解决，谢谢。之前建的老机器人不知道什么原因挂了

Y C ***@***.***> 于 2023年2月11日周六 10:56写道：

**Comment by eryajf** [comment]
也许是时间久了，给回收了

**Comment by iblogc** [comment]
好像是和名字有关，我有两个机器人，一个机器人名称带ChatGPT就挂了，另一个名字里没有ChatGPT就好的

**Comment by eryajf** [comment]
> 好像是和名字有关，我有两个机器人，一个机器人名称带ChatGPT就挂了，另一个名字里没有ChatGPT就好的

这个问题在置顶问题中已经明确讲过，尽量避开这个名字
