### ISSUE TITLE
和机器人说话提示错误，您看看是docker没运行好么

### ISSUE THREAD

**Issue by auvgfw** [eryajf/chatgpt-dingtalk#30]
45678900',
      },
    };
    const requiredFields = {
      payload: {
        firstName: 'Example',
        lastName: 'User',
        email: 'example.user@mailinator.com',
        password: 'TestPass12345678900',
      },
    };
    const userData = {
      firstName: 'Example',
      lastName: 'User',
      email: 'example.user@mailinator.com',
      password: 'TestPass12345678900',
    };
    const spy = sinon.spy(validator, 'validate');
    const spySchema = sinon.spy(userSchemas, 'registerSchema');
    const spyUserModel = sinon.spy(userModel, 'createUser');
    const spyHelper = sinon.spy(helper, 'getToken');
    const spySendEmail = sinon.spy(mailer, 'sendVerificationEmail');
    const spySendEmailFunction = sinon.spy(emailTemplate, 'sendVerificationEmail');
    try {
      await UserController.registerUser(req, res);
    } catch (error) {
      expect(error).to.be.an.instanceOf(Error);
    }
    expect(spy.calledOnce).to.be.true;
    expect(spySchema.calledOnceWithExactly(requiredFields)).to.be.true;
    expect(spyUserModel.calledOnceWithExactly(userData)).to.be.true;
    expect(spyHelper.calledOnce).to.be.true;
    expect(spySendEmail.calledOnce).to.be.true;
    expect(spySendEmailFunction.calledOnce).to.be.true;
    validator.validate.restore();
    userSchemas.registerSchema.restore();
    userModel.createUser.restore();
    helper.getToken.restore();
    mailer.sendVerificationEmail.restore();
    emailTemplate.sendVerificationEmail.restore();
  });

  it('should throw an error if res.status is not 200', async () => {
    const req = {

**Comment by eryajf** [comment]
这个提示信息我没有看懂，看起来像是js的语法，请问是不是弄错了

**Comment by auvgfw** [comment]
没事了，已经调试好了。。谢谢您了

另外我想问问，群里不同人@机器人的话，会分别得到回答么？还是说机器人会把所有人问的问题混起来当成一个语境

**Comment by eryajf** [comment]
不同的人应该是不一样的
