### ISSUE TITLE
麻烦问下预计什么时候支持gpt-4o呀

### ISSUE THREAD

**Issue by lifeishimeizi** [eryajf/chatgpt-dingtalk#303]
麻烦问下预计什么时候支持gpt-4o呀

**Comment by hkthomas** [comment]
看了下，用了这个库go-openai，这个库不支持gpt-4o哦，怕是有的等了。

**Comment by hkthomas** [comment]
[chatgpt-dingtalk.zip](https://github.com/user-attachments/files/16309093/chatgpt-dingtalk.zip)
这是我自用的支持GPT4o的版本，仅编译了WIN的。
