### ISSUE TITLE
请求openai失败了

### ISSUE THREAD

**Issue by LoveClears** [eryajf/chatgpt-dingtalk#304]
![image](https://github.com/user-attachments/assets/81817381-e2c9-47d1-bf09-faf79269d065)
想问一下,之前都是好好的,然后今天突然弹出这个错误,因为东西是别人部署的,我也不知道怎么解决!

目前已经在网站上创建了key 并且直接修改了yml配置,
ecs-user@asinking-proxy:~/chatgpt-dingtalk$ ./chatgpt-dingtalk
2024/07/18 15:55:58 INFO [?? The Server Is Running On Stream Mode]
但是错误还是一样的!

**Comment by LoveClears** [comment]
"error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }

应该是APIKEY的问题

**Comment by LoveClears** [comment]
但是我改了之后 重新运行程序 错误为什么还是提示一样的?

**Comment by LoveClears** [comment]
{"error":{"code":"unsupported_country_region_territory","message":"Country, region, or territory not supported","param":null,"type":"request_forbidden"}}ecs-user@asinking-proxy:~/chatgpt-dingtalk$ 
好像是被ban了,还有什么解决办法吗,之前是在阿里云香港服务器上做的,我看yml配置上好像有
http_proxy: "socks5://127.0.0.1:10808"

**Comment by hkthomas** [comment]
配置截个图看看。
