### ISSUE TITLE
Docker无法启动

### ISSUE THREAD

**Issue by mattholy** [eryajf/chatgpt-dingtalk#308]
按照README启动DOCKER不成功

日志如下：
```
docker compose up
[+] Running 1/1
 ✔ Container Dingtalk-GPT  Recreated
Attaching to Dingtalk-GPT
Dingtalk-GPT  | 2024/08/02 16:05:30 yaml: unmarshal errors:
Dingtalk-GPT  |   line 14: cannot unmarshal !!int `600` into time.Duration
Dingtalk-GPT exited with code 0
```

**Comment by eryajf** [comment]
> 按照README启动DOCKER不成功
> 
> 日志如下：
> 
> ```
> docker compose up
> [+] Running 1/1
>  ✔ Container Dingtalk-GPT  Recreated
> Attaching to Dingtalk-GPT
> Dingtalk-GPT  | 2024/08/02 16:05:30 yaml: unmarshal errors:
> Dingtalk-GPT  |   line 14: cannot unmarshal !!int `600` into time.Duration
> Dingtalk-GPT exited with code 0
> ```

看看是不是你的变量类型不对

**Comment by mattholy** [comment]
我啥都没改直接启动的。
虽然我不懂go，但是gpt帮我破案了一波，时长参数配置文件默认是600，改成600s就跑起来了
