### ISSUE TITLE
钉钉也挺逆天的

### ISSUE THREAD

**Issue by Zoumachuan** [eryajf/chatgpt-dingtalk#31]
从wechat-chatgpt过来的，刚注册五分钟的账号啥也没发就被封了，蚌埠住了

**Comment by auvgfw** [comment]
操那么恐怖么。。我是怕wechat封号才转到钉钉来的。。
不过，有意思的是，我创建钉钉机器人的时候 如果取名为chatgpt，就会提示系统繁忙，无法创建
而且还自己弹出来了付费的信息，9800一年，一万次openai调用
所以我觉得他们封号。。可能是因为想自己挣这个钱

**Comment by eryajf** [comment]
> 如果取名为chatgpt，就会提示系统繁忙，无法创建

竟有如此奇事儿

**Comment by taiwuliao** [comment]
是@不了了吗，我@机器人提示由于系统维护@能力暂不可用

**Comment by eryajf** [comment]
> 是@不了了吗，我@机器人提示由于系统维护@能力暂不可用

参考下这个：https://github.com/eryajf/chatgpt-dingtalk/issues/29
