### ISSUE TITLE
机器人太累了，让她休息会儿，过一会儿再来请求。

### ISSUE THREAD

**Issue by GittenHub** [eryajf/chatgpt-dingtalk#32]
请问下，机器人回复：机器人太累了，让她休息会儿，过一会儿再来请求。这是什么原因

**Comment by eryajf** [comment]
客户端请求chatgpt服务端失败了

**Comment by binghan2000** [comment]
这个怎么解决？

**Comment by eryajf** [comment]
> 这个怎么解决？

是一直在报这个吗，还是偶尔，如果一直报，说明你的客户端到openai的客户端网络不通，如果是偶尔报，目前已经加了重试，还没有太好的办法
