### ISSUE TITLE
非linux部署，下载zip包，可执行文件部署的两个问题

### ISSUE THREAD

**Issue by STmission** [eryajf/chatgpt-dingtalk#33]
懒人使用可执行文件使用时的细节：
如果在使用下载对应zip包，非linux部署，进行chatgpt-dingtalk可执行文件的直接使用时，需更改如下：
1、目前使用可执行文件，会报错config.json不存在问题：
记得在下载zip包，解压之后，重新命名一下json文件为config.json即可。
2、在钉钉的开发平台中修改如下信息：
服务器出口IP
127.0.0.1
消息接收地址
http://chat.eryajf.net:8090/
目的是：请求的时候会请求到自己本机地址的服务器和对应端口

**Comment by STmission** [comment]
也想请问作者，我可以发视频和发文章，进行分享吗？
都会附上您的链接和署名

**Comment by eryajf** [comment]
> 也想请问作者，我可以发视频和发文章，进行分享吗？

当然可以，完全没有问题

**Comment by eryajf** [comment]
> 服务器出口IP
> 127.0.0.1

这个我倒是没有验证过，你在你的本地验证确实没有问题吗，如果没有问题，那看起来是钉钉会先走本地的网络进行请求
