### ISSUE TITLE
机器人太累了，让她休息会儿，过一会儿再来请求。

### ISSUE THREAD

**Issue by harrywoo** [eryajf/chatgpt-dingtalk#34]
超过97个tokens的文本就会报错，看起来有4000个token是completion的，这个是什么地方的限制吗。  
"error": {
    "message": "This model's maximum context length is 4097 tokens, however you requested 4995 tokens (995 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }

**Comment by eryajf** [comment]
官方文档对这里有介绍：https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens

再长的话的确就不行了。

**Comment by MyTrancy** [comment]
> 官方文档对这里有介绍：https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens
> 
> 再长的话的确就不行了。

我也遇到这个问题了，我提问的字数也就十来个，出现这个提示之后，我甚至只用简单的你好，hello来提问，但是仍然报这个错；
![image](https://user-images.githubusercontent.com/25986778/218445296-613c4a4f-67c8-468c-93bf-7a5ebc9f3eb4.png)

而且同样的问题，在web提问，和在钉钉里提问，给出的答案不一样，比方我提问“你是谁”，web会明确给出自己叫gpt，但是钉钉的回答是一个模板
![image](https://user-images.githubusercontent.com/25986778/218445233-033bcf59-42dc-4f53-b68a-8ddabbf183b5.png)

**Comment by MyTrancy** [comment]
> 官方文档对这里有介绍：https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens
> 
> 再长的话的确就不行了。

而且我有预感这玩意会被ban， 本身这个需要门槛（梯子加境外手机号）但是做成这种机器人之后，等等于给一批人搭了梯子。老哥，我风紧扯呼，溜了溜了

**Comment by eryajf** [comment]
> 出现这个提示之后，我甚至只用简单的你好，hello来提问，但是仍然报这个错

我大概知道原因了，这是每次都带上了之前的内容，导致的这个问题，晚些时候我有空了会尝试修复这个问题

**Comment by auvgfw** [comment]
我这里也是，昨天特别高频率的提示机器人太累了。
不过我也试了试，去官方api的playgroud发送请求，同样会高频率的返回
The server had an error while processing your request. Sorry about that

**Comment by eryajf** [comment]
今天对整个交互模式进行了重构，可以升级到最新版本试用一下，看看效果如何

如果再报超出了这个限额，可以发送重置关键字，重置上下文

**Comment by auvgfw** [comment]
> 今天对整个交互模式进行了重构，可以升级到最新版本试用一下，看看效果如何
> 
> 如果再报超出了这个限额，可以发送重置关键字，重置上下文

是指的“清空会话”么

**Comment by eryajf** [comment]
@auvgfw 看下README更新的说明，你艾特机器人，发送帮助俩字，会有个帮助菜单

**Comment by auvgfw** [comment]
请问本次更新推送到docker hub里了么？还是需要clone下来自己做docker image？

**Comment by eryajf** [comment]
@auvgfw 不需要自己打镜像，每次代码更新，action会自动打镜像，你需要做的是删除本地的latest镜像，然后pull最新的latest镜像即可。

**Comment by auvgfw** [comment]
我删了重新pull了。。但是docker images显示 docker.mirrors.sjtug.sjtu.edu.cn/eryajf/chatgpt-dingtalk:latest 这个镜像是2month ago的。。是不是最新的action还没完成呢。。

**Comment by eryajf** [comment]
@auvgfw readme里我已经换了个新的加速地址，应该是这个加速地址不再更新或者更新比较慢。

```
docker pull dockerproxy.com/eryajf/chatgpt-dingtalk:latest
```

下载这个是最新的。
