### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by binghan2000** [eryajf/chatgpt-dingtalk#35]
gtp api status code not equals 200, code is 429 ,details:  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by eryajf** [comment]
通过这里查看你的免费额度是不是用完了：

https://platform.openai.com/account/usage
