### ISSUE TITLE
模型用的text-davinci-003，怎么会这么拉跨，是不是需要哪里调节参数

### ISSUE THREAD

**Issue by thechen130** [eryajf/chatgpt-dingtalk#39]
![image](https://user-images.githubusercontent.com/74664452/218442154-279d48ae-5b12-4665-ac9e-0bf0b7384655.png)
![image](https://user-images.githubusercontent.com/74664452/218442214-d70b89dd-7035-470d-88b7-2e31dc55488d.png)

**Comment by eryajf** [comment]
目前官方提供出来的可以对接，这就是最新的

可以尝试给它一些前置描述，来优化他的应答， 比如发问题之前带上： 以下是与AI助手的对话。助手乐于助人，富有创造力，聪明且非常友好。

**Comment by eryajf** [comment]
因为接口开放的是GPT3，网页版的应该是3.5，所以更智能一些

**Comment by zanderzhng** [comment]
> 因为接口开放的是GPT3，网页版的应该是3.5，所以更智能一些

了解了。原来确实还是有差距的。不知道以后付费版会不会给更好的API。

**Comment by zanderzhng** [comment]
> 因为接口开放的是GPT3，网页版的应该是3.5，所以更智能一些

我今天注意到 [chatgpt_telegram_bot](https://github.com/karfly/chatgpt_telegram_bot) 里提到他是3.5，不知道是不是用了另一个接口，明天有时间的话我会看看，你也可以参考下。

`This repo is ChatGPT re-created with GPT-3.5 LLM as Telegram Bot. And it works great.`

**Comment by eryajf** [comment]
我看了下他的代码，话说他用的也还是 3.0 呀 https://github.com/karfly/chatgpt_telegram_bot/blob/f2bc61714647c889a34401fce2b72e7bd070f28c/bot/chatgpt.py#L42

不过我稍微体验了一下，的确看起来效果更好一些。

**Comment by zanderzhng** [comment]
> 我看了下他的代码，话说他用的也还是 3.0 呀 https://github.com/karfly/chatgpt_telegram_bot/blob/f2bc61714647c889a34401fce2b72e7bd070f28c/bot/chatgpt.py#L42
> 
> 不过我稍微体验了一下，的确看起来效果更好一些。

我到公司了，看了下代码，发现你们用的都是 openai 的官方库，也默认是 003 的模型，所以应该没区别。
温度默认设置不一样，但是这个影响应该不大。

**Comment by thechen130** [comment]
应该是text-chat-davinci-003而不是text-davinci-003，但是可能需要作者修改一些相应代码

**Comment by ZephyrTan** [comment]
回复确实有点拉胯，近期会优化吗
