### ISSUE TITLE
上下文问题和unmarshal request body failed: unexpected end of JSON input问题

### ISSUE THREAD

**Issue by jaylonluo** [eryajf/chatgpt-dingtalk#4]
1用最新代码部署上下文还是不能用。
2.钉钉加机器人验证接口时依旧会出现unmarshal request body failed: unexpected end of JSON input报错。 推测与钉钉验证接口参数有关。实际使用机器人时没有这个报错。

**Comment by eryajf** [comment]
1.确认是否是最新版的代码，我这边测试上下文已经可用。另外确认下配置文件中 session_timeout 的值，这个是上下文的超时时间。
2. 报这个错误的时候，看看程序的输出内容，我怀疑验证的时候钉钉没有返回任何内容，所以会报那个错误。
