### ISSUE TITLE
在同一个群聊里，是共享一个会话吗？

### ISSUE THREAD

**Issue by zanderzhng** [eryajf/chatgpt-dingtalk#40]
共享会话的话，可以根据其他人的问题承接讨论。

不共享的话，大家各自问自己的。

各有利弊，想了解下现在是怎么设置的？

**Comment by auvgfw** [comment]
我经过实验发现是不共享

**Comment by zanderzhng** [comment]
> 我经过实验发现是不共享

好处是不会干扰到别人，坏处是没法像公共讨论一样。谢谢实验。

**Comment by auvgfw** [comment]
如果想讨论的话可以把别人的问题，或者机器人的回复复制下来。。

**Comment by eryajf** [comment]
@zanderzhng 强烈建议更新到最新版本进行体验，交互上优化了很多。

**Comment by zanderzhng** [comment]
> @zanderzhng 强烈建议更新到最新版本进行体验，交互上优化了很多。

确实强了不少。
另外关于API的问题，我今天注意到这么一条提示。估计确实是很老的版本了。新版本只有网页版才能用。
<img width="263" alt="image" src="https://user-images.githubusercontent.com/867749/219583762-0acecef5-a5d9-4a7a-8efe-a47873222308.png">
