### ISSUE TITLE
有时候机器人会的第一个字母是？

### ISSUE THREAD

**Issue by binghan2000** [eryajf/chatgpt-dingtalk#41]
有时候机器人会的第一个字母是？还有问问题，然后它回答的是昨天的问题延续，是网络的问题？还是？

**Comment by eryajf** [comment]
带问号应该是程序的bug，问题的延续是因为有上下文的交互，这块儿我看看怎么再优化一下

**Comment by binghan2000** [comment]
嗯，而且有时候，隔了好久会回答很久之前的问题。

**Comment by eryajf** [comment]
今天对整个交互模式进行了重构，这两个问题都会得到解决，可以升级到最新版本试用一下，看看效果如何

**Comment by zhichen** [comment]
最新版的镜像也发布了吗？

**Comment by eryajf** [comment]
是的，参考readme



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月17日 13:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [eryajf/chatgpt-dingtalk] 有时候机器人会的第一个字母是？ (Issue #41) |

最新版的镜像也发布了吗？
