### ISSUE TITLE
Outgoing机制一直显示在维护中？是不是凉凉了？

### ISSUE THREAD

**Issue by zccbbg** [eryajf/chatgpt-dingtalk#42]
最近添加的时候，提示：该功能正在维护中，给你带来不便敬请见谅。是不是钉钉不给加这个了？
![image](https://user-images.githubusercontent.com/10760556/218896043-59492893-64dc-4fac-8a50-6dbbbb411568.png)

**Comment by eryajf** [comment]
有没有截图看下，也许是ding做了什么限制

**Comment by zanderzhng** [comment]
添加的时候名称不能包含chatgpt。

**Comment by zccbbg** [comment]
> 有没有截图看下，也许是ding做了什么限制

![image](https://user-images.githubusercontent.com/10760556/218896103-0a5819d6-1ab9-4b4d-94bf-98efa755cee8.png)

**Comment by eryajf** [comment]
@zccbbg 这里应该添加的是应用中创建的机器人，这个过程不涉及到outgoing这个选项，看起来你这个添加的应该是普通机器人吧

**Comment by zccbbg** [comment]
明白了，感谢

**Comment by allanwxl** [comment]
申请个内部群就有这个功能了

**Comment by baodingsnow** [comment]
> 申请个内部群就有这个功能了

和这个没有关系
