### ISSUE TITLE
您好，这个怎么样修改可以让企业微信可以用呢

### ISSUE THREAD

**Issue by edu-hui** [eryajf/chatgpt-dingtalk#45]

**Comment by eryajf** [comment]
我没有了解过企业微信是否支持这种交互性机器人，如果支持的话，那接入会很容易

**Comment by auvgfw** [comment]
这个我说两句，几个机器人我都对比过

个人微信;官方不支持机器人，靠外挂实现，会被封号
企业微信：可以在内部群（全由一个组织内成员组成的群）里部署机器人，外部群不行。内部群的机器人是企业微信官方支持的，有接口。
但是，如果你想做一个企业微信机器人，像微信一样拉人进群，使用机器人，那是不可能的。因为那么拉来的人算外部群。
必须让人加入你的企业，才是内部群。
钉钉：就是咱们这个了，同样是官方支持的。

**Comment by eryajf** [comment]
感谢反馈，我测试过，钉钉这个其实也是内部群，没办法加外部人。

企业微信大概看了下，貌似也能接收机器人的回调，似乎有戏。

**Comment by eryajf** [comment]
企业微信能对接，但是有一个问题就是，企业微信后台创建的应用，无法添加到群里， 

> 企业微信：可以在内部群（全由一个组织内成员组成的群）里部署机器人，外部群不行。

@auvgfw 你说的这个我没有找到是怎么弄得。

所以企微应该只支持一对一跟应用聊，这个目前先不支持了

**Comment by edu-hui** [comment]
有时间的话，还是希望可以支持一下，现在慢慢的企业微信还是要用的多一些，企微的应用可以设置一对多的。

**Comment by eryajf** [comment]
应用一对多发消息，跟在群聊里和机器人聊天概念还是不一样的。

暂时不打算支持了，其实这个项目已经完成了80%的能力，你有兴趣可以fork出来，集成到企微里边。
