### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by binad2022** [eryajf/chatgpt-dingtalk#47]
[WARNING]2023/02/16 09:05:35 logger.go:33: send message error: %v 
 Post "": unsupported protocol scheme ""
[WARNING]2023/02/16 09:05:35 logger.go:33: process request failed: %v
 Post "": unsupported protocol scheme ""

不知道啥问题

**Comment by eryajf** [comment]
是从来就没有成功过，还是偶尔会报这个呢

**Comment by binad2022** [comment]
> 是从来就没有成功过，还是偶尔会报这个呢

昨天是成功了，升级了新版之后就g了

**Comment by eryajf** [comment]
升级之后一次也没有成功过吗，你给机器人发的什么消息，报的这个错误呢，请给内容给详细点

**Comment by binad2022** [comment]
> 升级之后一次也没有成功过吗，你给机器人发的什么消息，报的这个错误呢，请给内容给详细点

比如查询北京天气之类的 今天一次都没成功过

**Comment by tanaer** [comment]
同样问题，刚安装配置完， 日志 如下

dingtalk callback parameters: &public.ReceiveMsg{ConversationID:"", AtUsers:[]struct { DingtalkID string "json:\"dingtalkId\"" }(nil), ChatbotUserID:"", MsgID:"", SenderNick:"", IsAdmin:false, SessionWebhookExpiredTime:0, CreateAt:0, ConversationType:"", SenderID:"", ConversationTitle:"", IsInAtList:false, SessionWebhook:"", Text:public.Text{Content:""}, RobotCode:"", Msgtype:""}
[WARNING]2023/02/16 18:46:30 logger.go:33: send message error: %v 
 Post "": unsupported protocol scheme ""
[WARNING]2023/02/16 18:46:30 logger.go:33: process request failed: %v
 Post "": unsupported protocol scheme ""

**Comment by eryajf** [comment]
你们最新版是通过docker部署的吗，随后我看看能否复现下

**Comment by tanaer** [comment]
> 你们最新版是通过docker部署的吗，随后我看看能否复现下

通过docker一键部署的 和 下载二进制文件启动 都会这样。

**Comment by tanaer** [comment]
使用0.1.1 可以了。谢谢大佬。

**Comment by eryajf** [comment]
那应该是调试的时候返回的信息为空所以会有这个错误，可忽略
