### ISSUE TITLE
串聊次数过多后报错

### ISSUE THREAD

**Issue by AngryBigCat** [eryajf/chatgpt-dingtalk#48]
![image](https://user-images.githubusercontent.com/14774417/219522705-59fac4ea-020f-4696-b929-1235e735c379.png)

**Comment by AngryBigCat** [comment]
切回单聊模式，就又正常了

**Comment by eryajf** [comment]
有最大字符限额，到达限额之后，艾特机器人发送 重置 然后再次进入串聊就可以了



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月17日 09:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [eryajf/chatgpt-dingtalk] 串聊次数过多后报错 (Issue #48) |

切回单聊模式，就又正常了
