### ISSUE TITLE
通过docker 部署之后@机器人没有回复

### ISSUE THREAD

**Issue by houko** [eryajf/chatgpt-dingtalk#5]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/12625278/207549573-9f419665-5afa-46dc-827f-5cf28d93496e.png">

**Comment by eryajf** [comment]
可查看一下应用日志输出，如果输出内容为 回调参数为空,以至于无法正常解析,请检查原因，那建议新建个机器人试试。有好几个朋友在这个问题上踩坑了

**Comment by houko** [comment]
没有输出任何内容哦

**Comment by eryajf** [comment]
那应该就是你的服务，没能让钉钉访问到，需要检查你的配置流程。
