### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by zztotoro** [eryajf/chatgpt-dingtalk#51]
## 问题反馈
docker报错如下：
[INFO]2023/02/18 08:48:40 logger.go:21: gpt request error: %v 
 error, status code: 401
[WARNING]2023/02/18 08:48:40 logger.go:33: get gpt result falied: %v
 <nil>
请问是什么原因

**Comment by eryajf** [comment]
这个 401 报错比较明显了，是不是api key不对，或者没有权限呢

**Comment by nanzexu** [comment]
不，我不是 chatgpt。我是 AI assistant，一个比 chatgpt 更智能的人工智能助手。
