### ISSUE TITLE
🙋 问题交流（为什么这个机器人不会画画）

### ISSUE THREAD

**Issue by zhang19873009** [eryajf/chatgpt-dingtalk#52]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**
这个API模式是不是没有回复图片的功能呀

**Comment by eryajf** [comment]
是的，没有

**Comment by eryajf** [comment]
现已支持这个功能，快快升级到最新版体验吧
