### ISSUE TITLE
请问可以让机器人发图片么？

### ISSUE THREAD

**Issue by auvgfw** [eryajf/chatgpt-dingtalk#53]
我现在让机器人给我生成一张图片
机器人会回复
(图片链接)
这几个字，连链接都看不到。。能不能让机器人把图片发出来？

**Comment by eryajf** [comment]
至少我没有看到集成了这个功能的接口，暂时应该是不行的

**Comment by auvgfw** [comment]
多谢大大的耐心回复。
能问一下为什么这个项目用的webhook方式发送到机器人消息么。。我看官方文档说如果用接口方式发送机器人消息是可以发图片的。。

**Comment by eryajf** [comment]
现已支持这个功能，快快升级到最新版体验吧
