### ISSUE TITLE
docker部署升级后无与api交互的输出了

### ISSUE THREAD

**Issue by starpipi** [eryajf/chatgpt-dingtalk#54]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

原docker部署的0.0.8版本正常使用。近期看到版本有更新，下载0.1.1新的镜像部署后。
运行测试curl只有参数日志。 没有与openai的接口调用日志了。切换回低版本无问题，请问是哪里有变化了？
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/3281064/221453591-a7e06bb3-1bc1-4915-9a58-c0e07738f423.png">

**Comment by eryajf** [comment]
这个只是把那句输出日志的代码去掉了，实际使用上没有太大变化

**Comment by starpipi** [comment]
好的我再试一下。
我早上尝试的时候是先发现群里面at机器人没反应了 才去看日志的。。。

那现在是否还有别的方式能辅助定位是否是正常运行，还是说是与钉钉之间交互有其他问题呢？

**Comment by starpipi** [comment]
确认可用，暂无其他问题，只是隐藏了日志
