### ISSUE TITLE
🙋 GPT3.5模型出来了

### ISSUE THREAD

**Issue by ZephyrTan** [eryajf/chatgpt-dingtalk#57]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

**Comment by 51070147** [comment]
https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**Comment by eryajf** [comment]
在做了，在做了
