### ISSUE TITLE
现在上下问的代码是不是有点问题？

### ISSUE THREAD

**Issue by WinMin** [eryajf/chatgpt-dingtalk#61]
现在上下问的代码是不是有点问题？
进入串聊后， 好像上下文不起作用了。

load station failed: open openaiCache/116812370225695275: no such file or directory

看来下日志，是cache没保存的样子。

**Comment by eryajf** [comment]
应该有bug，我稍后修下

**Comment by WinMin** [comment]
> 应该有bug，我稍后修下

review 了下代码， 猜测是这里出问题了

https://github.com/eryajf/chatgpt-dingtalk/blob/addb086c9168860ae71f6319d9cd2238437d8b6e/main.go#L136

这里保存的是nick

然后用的时候用的是id

![image](https://user-images.githubusercontent.com/18380453/222429653-dc42b67b-fcf1-4878-9f6e-716da8ff7ca4.png)

**Comment by WinMin** [comment]
我提PR吧

**Comment by eryajf** [comment]
非常欢迎，其实我想把这个地方改一下，存到cache里好了，不再创建文件保存了



| |
eryajf
|
|
***@***.***
行者常至，为者常成！
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月02日 20:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [eryajf/chatgpt-dingtalk] 现在上下问的代码是不是有点问题？ (Issue #61) |

我提PR吧

**Comment by WinMin** [comment]
> 非常欢迎，其实我想把这个地方改一下，存到cache里好了，不再创建文件保存了 | | eryajf | | ***@***.*** 行者常至，为者常成！ |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月02日 20:35 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [eryajf/chatgpt-dingtalk] 现在上下问的代码是不是有点问题？ (Issue #61) | 我提PR吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

如果你要修改存到cache， 那我就不动代码了，如果只是修这个 bug ，我可以提一下。看你

**Comment by eryajf** [comment]
@WinMin 放cache好一些，省去与磁盘交互了，那等下，我来改下吧
