### ISSUE TITLE
回调消息中的 SenderStaffId 字段为空字符串

### ISSUE THREAD

**Issue by fantasticmao** [eryajf/chatgpt-dingtalk#63]
如果创建的 [机器人类型](https://open.dingtalk.com/document/orgapp/robot-overview#bb6008407a6y1) 是「自定义机器人」的话（aka 直接在群聊里创建的智能群助手），那么从钉钉接收回调消息的 `SenderStaffId` 会是空字符串，进而导致一些功能不可用。。比如串聊和回复 at 功能

<img width="650" alt="image" src="https://user-images.githubusercontent.com/20675747/222479234-e75b4419-d4a5-4dea-8f29-2bcea4b26884.png">

https://github.com/eryajf/chatgpt-dingtalk/blob/d4d748211710cfbae3ce7354dae19eebc0618b83/main.go#L88-L94

https://github.com/eryajf/chatgpt-dingtalk/blob/d4d748211710cfbae3ce7354dae19eebc0618b83/main.go#L128-L137

我看钉钉的文档，这个 `SenderStaffId` 字段好像是非必填的，我们这个机器人当前是不是不支持「自定义机器人」的类型啊，后续是否有计划兼容一下呢。

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/20675747/222477314-087c243d-90b7-4c92-9d53-b11369f301e3.png">

**Comment by eryajf** [comment]
你说的自定义机器人，指的是创建的时候开启outgoing功能的这个机器人吗，貌似这个outgoing功能官方对其时隐时现的，经常看不到这个功能，比如今天我打算创建，说该功能正在维护

当然，后续如果这个功能稳定，支持也未尝不可

**Comment by fantasticmao** [comment]
@eryajf 你好 eryajf，感谢回复！

我说的自定义机器人创建方式是：

```
1. 打开钉钉群聊，点击右上角「群设置」
2. 下拉点击「机器人」
3. 点击「添加机器人」
4. 下拉点击「自定义（通过Webhook接入自定义服务）」
5. 点击蓝色的「添加」按钮
6. 填写必要字段 && 勾选「是否开启Outgoing机制」 && 填写「POST 地址」和「Token」
7. 点击「完成」
```

我一直都是用这个机器人接入的，整体功能在我这边看来是稳定的，除了名字好像不能叫 ChatGPT 之外。。例如，这个例子 https://github.com/eryajf/chatgpt-dingtalk/issues/29#issuecomment-1451231366

**Comment by fantasticmao** [comment]
因为缺少钉钉的「开发者权限」（这个权限估计要向公司的 HR / 老板申请），所以创建不了 [README.md](https://github.com/eryajf/chatgpt-dingtalk#%E7%AC%AC%E4%B8%80%E6%AD%A5%E5%85%88%E5%88%9B%E5%BB%BA%E6%9C%BA%E5%99%A8%E4%BA%BA) 里提及的机器人。。

<img width="852" alt="image" src="https://user-images.githubusercontent.com/20675747/222643890-cd77ae75-7d3c-4e3c-b6fc-f536ecf548b6.png">

如果后续打算支持我说的「自定义机器人」，你那边没有时间的话，可以把你的想法和实现方案和我说一下，我来提个这个 PR

**Comment by eryajf** [comment]
我理解了，看起来这种方案似乎比管理后台创建机器人的方案更加优雅一些，只是我这边目前创建的确不让选择这个选项

<img width="600" alt="image" src="https://user-images.githubusercontent.com/33259379/222666112-e6a26c62-ed1c-46e7-aab2-e89668c4b786.png">

当我这里能成功创建这一类型的机器人之后，我会尝试对这一功能进行支持。

当然，也欢迎你的PR，如果这个方案与后台创建机器人的方案区别就是那个 SenderStaffId 的话，那处理起来也比较简单，找一个可用的用户标识就行了。

**Comment by iblogc** [comment]
好像我给挖坑了😟cache key 改为 SenderStaffId  没注意到调试模式和outgoing下没有值（outgoing 我之前建机器人都没见到过，今天是第一次看到😂）如果要实现你说的可以回滚下这两个点，自己可以本地docker build下
![image](https://user-images.githubusercontent.com/3283023/222683498-7589273e-5875-43ab-bd70-007329e941dc.png)

**Comment by fantasticmao** [comment]
@iblogc 你好 iblogc，感谢回复！

我已经找到这个版本的 docker image 并且重新部署了😂

**Comment by fantasticmao** [comment]
@eryajf 你好 eryajf，我把我的个人联系方式，发送到你的 GitHub 主页的邮箱上了，可以帮忙创建一下测试环境
