### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by itissika** [eryajf/chatgpt-dingtalk#64]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**
Nginx日志：
59.82.84.35 - - [03/Mar/2023:02:55:57 +0800] "POST / HTTP/1.1" 405 172 "-" "okhttp/3.5.0"
docker日志：[INFO]2023/03/02 18:49:42 logger.go:21: Start Listen On  :8090
![image](https://user-images.githubusercontent.com/126492354/222531805-6a8c9c77-4a28-426a-9cc1-25cccaf59236.png)

大佬我是小白一个，本来好好的，不知道怎么搞的，就用不了了。感觉好像Nginx反向代理不起作用，post不到docker里面去，这是什么问题导致的呢？

**Comment by eryajf** [comment]
如果不熟悉，可以先跳过Nginx的步骤，直接使用 ip:port

**Comment by asdfsa1314** [comment]
> 如果不熟悉，可以先跳过Nginx的步骤，直接使用 ip:port

目前是openAI 的后台接口改变了吗？经常连接超时该如何解决

**Comment by s0ng1** [comment]
你好，gpt3.5也是用的text-davinci-003，是不是之前部署的不需要重新部署了？

**Comment by eryajf** [comment]
> 目前是openAI 的后台接口改变了吗？经常连接超时该如何解决

服务器使用境外的，或者给服务器加个代理，目前api接口被墙

**Comment by eryajf** [comment]
> 你好，gpt3.5也是用的text-davinci-003，是不是之前部署的不需要重新部署了？

不是，这俩不一样，建议部署最新的，体验非常好

**Comment by s0ng1** [comment]
> > 你好，gpt3.5也是用的text-davinci-003，是不是之前部署的不需要重新部署了？
> 
> 不是，这俩不一样，建议部署最新的，体验非常好

是的，已更新，好用的不得了。哈哈，可以去openai充值去了。

**Comment by zhang19873009** [comment]
gpt3.5串聊模式不行了？我的上下文感觉没用呢

**Comment by eryajf** [comment]
> gpt3.5串聊模式不行了？我的上下文感觉没用呢

我这边验证没有问题

**Comment by zhang19873009** [comment]
> 

好的，我再看看，谢谢

**Comment by zhang19873009** [comment]
你们问机器人今天的日期，接口怎么回复呀。我的机器人回答不了
<img width="533" alt="image" src="https://user-images.githubusercontent.com/13284821/222662334-b4a09be0-d1ea-4d1a-96b7-232767fec50e.png">

**Comment by eryajf** [comment]
@asdfsa1314 @MutouLee 更改更新的最新版本支持配置proxy，可升级到最新版本添加proxy避免这个问题。

**Comment by MutouLee** [comment]
> @asdfsa1314 @MutouLee 更改更新的最新版本支持配置proxy，可升级到最新版本添加proxy避免这个问题。

就是刚部署的最新版，麻烦问下如何设置proxy ？

**Comment by eryajf** [comment]
如果你是docker部署，在环境变量中传入 `HTTP_PROXY`进行配置：

```
# 运行项目
$ docker run -itd --name chatgpt -p 8090:8090 -e APIKEY=换成你的key -e SESSION_TIMEOUT=600 -e HTTP_PROXY="" -e DEFAULT_MODE="单聊" --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest
```

使用 config.json 的话同理

**Comment by MutouLee** [comment]
> 如果你是docker部署，在环境变量中传入 `HTTP_PROXY`进行配置：
> 
> ```
> # 运行项目
> $ docker run -itd --name chatgpt -p 8090:8090 -e APIKEY=换成你的key -e SESSION_TIMEOUT=600 -e HTTP_PROXY="" -e DEFAULT_MODE="单聊" --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest
> ```
> 
> 使用 config.json 的话同理

HTTP_PROXY=""
这个参数怎么填啊？
经过测试，国内服务器报上述错误，我用海外服务器同样的方法步骤部署，一切正常了。
所以，我猜测应该是国内最近两会原因导致的，如果是这样的话，HTTP_PROXY=""设置后能否解决？ 具体怎么填麻烦指教，不胜感激。

**Comment by eryajf** [comment]
首先你的服务器得配置有代理，然后启动服务的时候，把代理地址配置进去就可以了。

比如我的服务器配置了代理，会有这些信息：

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/33259379/222685392-bdf59aa2-2130-4244-a9d7-db5761d50283.png">

那么启动服务的时候，把地址带上去就可以了。

```
# 运行项目
$ docker run -itd --name chatgpt -p 8090:8090 -e APIKEY=换成你的key -e SESSION_TIMEOUT=600 -e HTTP_PROXY="http://127.0.0.1:15777" -e DEFAULT_MODE="单聊" --restart=always  dockerproxy.com/eryajf/chatgpt-dingtalk:latest
```

至于服务器怎么配置代理，你得看你的代理的说明文档。

**Comment by MutouLee** [comment]
> 

明白了，您意思是首先需要一个科学上网的梯子，然后服务器本地配置好代理，然后启动时候用参数加上代理地址，是吧？

**Comment by eryajf** [comment]
对

**Comment by itissika** [comment]
> 如果不熟悉，可以先跳过Nginx的步骤，直接使用 ip:port

完美，正常跑起来了，大佬牛。顺便让ai帮忙写了个flask把dalle也接了进去，话说dalle好贵啊，1张要1毛钱。
还有就是模型能改吗？我发现现在用的模型都是gpt-3.5-turbo-0301，快是快，就是质量不咋滴，这个在哪里改模型呢？

**Comment by baby9** [comment]
> > 如果不熟悉，可以先跳过Nginx的步骤，直接使用 ip:port
> 
> 完美，正常跑起来了，大佬牛。顺便让ai帮忙写了个flask把dalle也接了进去，话说dalle好贵啊，1张要1毛钱。 还有就是模型能改吗？我发现现在用的模型都是gpt-3.5-turbo-0301，快是快，就是质量不咋滴，这个在哪里改模型呢？

更好的模型要加钱，$20一个月
