### ISSUE TITLE
能否支持AccessToken的方式调用

### ISSUE THREAD

**Issue by GH6324** [eryajf/chatgpt-dingtalk#65]
大佬，能否支持AccessToken的方式调用ChatGPT，这样就能省api请求次数了，这是另外一个大佬写的项目，api和AccessToken都支持    https://github.com/Chanzhaoyu/chatgpt-web

再次感谢大佬们的无私奉献

**Comment by eryajf** [comment]
服务端部署，要求比较严格，所以目前这方面的很少有实现的
