### ISSUE TITLE
查询余额超时

### ISSUE THREAD

**Issue by fantasticmao** [eryajf/chatgpt-dingtalk#69]
我家是在路由器上设置科学上网的，所以在服务器上无需设置 http 代理，也是可以正常访问谷歌和 openai.com。

<img width="665" alt="image" src="https://user-images.githubusercontent.com/20675747/222940315-18aaabab-eff7-4134-9719-93383d2b0b35.png">

不过我试了一下最新版本的镜像，其它功能都是正常的，只有在查询余额时候，机器人没有回复。看了日志，似乎是代理配置有问题。

<img width="665" alt="image" src="https://user-images.githubusercontent.com/20675747/222940354-17d04432-198c-42ce-8332-4a70ccc16753.png">

看了一下代码，似乎是这儿没有对 `http_proxy`  配置项做空字符串的判断。

https://github.com/eryajf/chatgpt-dingtalk/blob/510d9c5324b100bc2423f002e2ace37cc3843d10/public/gpt.go#L13

**Comment by eryajf** [comment]
最新的代码已修复此问题
