### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by Facemax** [eryajf/chatgpt-dingtalk#71]
你好，eryaif
首先，我成功运您的项目，十分不错！
但我遇见一个问题，为什么我openai API key 在使用前是从不过期，在发起请求后，有效期就只有当天
那么每天都要进行更改api key。
我是使用docker 布置的
期待你的回复！
祝你每天开心！

**Comment by eryajf** [comment]
你说的这个有效期指的是在哪里看到的有效期呢，能否截图看看，这个项目并不需要每天重置key的

**Comment by Facemax** [comment]
![WX20230306-172830@2x](https://user-images.githubusercontent.com/19884263/223070453-29edb039-cfe2-4343-9b8f-0823a669414d.png)

**Comment by Facemax** [comment]
当我首次申请时候，last used 是从不，但接口被调用后，就只有一天有效期。
你有遇见吗

**Comment by eryajf** [comment]
这是最后用了这个key的时间，表示今天这个时间有用过，而不是表示今天过期

**Comment by Facemax** [comment]
感谢你，那我明白了。
