### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by relei1988** [eryajf/chatgpt-dingtalk#72]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**

通过后台用量查询发现，我们使用的是`GPT-3.5 Turbo-0301`

而询问网页版得到答案：

如果您想要使用OpenAI提供的API来访问我，而不是其他的模型（如GPT-3.5 Turbo-0301），您需要使用我在OpenAI平台上的模型ID。您可以使用以下命令检索我的模型ID：

Copy code
openai models list
这将显示您在OpenAI上可用的所有模型的列表，包括我的模型ID。我的模型ID是“davinci-codex”，您可以在API请求中使用它来使用我的模型。
在API请求中使用模型ID的示例：

```
import openai
openai.api_key = "YOUR_API_KEY"
model_engine = "davinci-codex"
prompt = "Hello, I am a language model."
completions = openai.Completion.create(
    engine=model_engine,
    prompt=prompt,
    max_tokens=10
)
```
在上面的示例中，我们使用了我的模型ID“davinci-codex”来初始化API请求，并使用它来获取生成的文本。请注意，您需要替换“YOUR_API_KEY”为您自己的OpenAI API密钥。

请问有无方法更改成这个model_engine？

**Comment by eryajf** [comment]
目前来说，模型好像比较多，而且不同的模型对应的接口以及请求方法也有差异，这块儿需要做一个梳理之后，才能进行个性化配置的支持

**Comment by relei1988** [comment]
原来如此，我以为直接在config里调整参数即可

**Comment by eryajf** [comment]
这个功能会很快支持，支持后的确就是在config里调整参数就行。

PS：支持的功能的确是这样用的，但背后的逻辑需要做一些处理

**Comment by relei1988** [comment]
ok非常感谢 期待更新

**Comment by eryajf** [comment]
最新发布的 v0.1.6 已支持配置模型。

**Comment by relei1988** [comment]
大佬神速

**Comment by relei1988** [comment]
> 目前有哪些模型，可以在哪里查看呢？在openai官网没有找到明确列表的地方

openai models list
这将显示您在OpenAI上可用的所有模型的列表

**Comment by eryajf** [comment]
> 目前有哪些模型，可以在哪里查看呢？在openai官网没有找到明确列表的地方

据我了解，至少有这些可以选择：

```
"gpt-3.5-turbo-0301"
"gpt-3.5-turbo"
"text-davinci-003"
"text-davinci-002"
"text-curie-001"
"text-babbage-001"
"text-ada-001"
"text-davinci-001"
"davinci-instruct-beta"
"davinci"
"curie-instruct-beta"
"curie"
"ada"
"babbage"
```

如果你对这块儿不够了解，那么使用默认的就好。
