### ISSUE TITLE
服务器已经开了科学上网，但应用似乎没有走代理。

### ISSUE THREAD

**Issue by LukerChen** [eryajf/chatgpt-dingtalk#79]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/6269043/223601866-8f2eb697-743c-4e35-aed0-43ef350910ad.png">
通过curl请求接口都是能够访问的，但是应用接口没法使用。

`[INFO]2023/03/08 02:11:25 logger.go:21: gpt request error: %v 
 Post "https://api.openai.com/v1/chat/completions": dial tcp 103.252.114.11:443: i/o timeout
[WARNING]2023/03/08 02:11:25 logger.go:33: get gpt result falied: %v`

**Comment by LukerChen** [comment]
> 能否看下你的代理配置是怎么写的，是不是没有配置好呢

curl请求能生效的喔。
以下是docker内的代理全局配置
`export http_proxy="http://172.17.0.1:7890"
  export https_proxy=$http_proxy`

其中127.17.0.1:7890是我配置在宿主机上的clash服务。

**Comment by eryajf** [comment]
你参考下我这篇文章改下配置试试：https://wiki.eryajf.net/pages/674f53/

**Comment by LukerChen** [comment]
> 你参考下我这篇文章改下配置试试：https://wiki.eryajf.net/pages/674f53/

搞定，谢谢！

**Comment by Midnight-719** [comment]
我想请问下 http_proxy 该如何设置，https://wiki.eryajf.net/pages/674f53/ 访问不了
