### ISSUE TITLE
用了香港的ECS，但是还是报错timeout，请问是什么原因呢

### ISSUE THREAD

**Issue by LiuNull** [eryajf/chatgpt-dingtalk#80]
ERROR RESTY Get "https://api.openai.com/dashboard/billing/credit_grants": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1

**Comment by LiuNull** [comment]
用的是压缩包方式部署的。
这是我的config.json文件，proxy直接用的本机公网ip
{
    "api_key": "sk-3FpkeR4aAsP1mgv34***********************",
    "model": "gpt-3.5-turbo",
    "session_timeout": 600,
    "http_proxy": "http://121.**.**.2:15732",
    "default_mode": "单聊"
}

**Comment by LiuNull** [comment]
直接curl 是可以访问的
![image](https://user-images.githubusercontent.com/19554995/223609639-f5e6be7d-63ed-43f4-9019-3d9e5af5be8b.png)

**Comment by eryajf** [comment]
香港的节点，是不是把http_proxy留空就可以了，之前有人测试香港节点不需要添加代理。

另外如果你确实想添加代理，那么地址直接使用 127.0.0.1 再试试

**Comment by LiuNull** [comment]
留空就可以了。现在可以成功跑起来，但是我在本地curl一个钉钉请求测试的时候，没有任何结果返回，请问是什么原因呢？这是后台的请求
![image](https://user-images.githubusercontent.com/19554995/223617905-85a210b3-aa4e-40e7-9c40-d3b642f354c1.png)

**Comment by LiuNull** [comment]
这是我本地curl的命令，没有返回任何结果或报错信息
![image](https://user-images.githubusercontent.com/19554995/223618612-83f9d5b5-60c3-4100-9e43-f67c6118ec7f.png)

**Comment by LiuNull** [comment]
不过我看好像openai的后台显示model usage已经用到了
![image](https://user-images.githubusercontent.com/19554995/223618885-89bdc3e6-7f6e-4337-883e-36afbd62113d.png)

**Comment by eryajf** [comment]
这是正常的，日志只打印了请求的参数，返回参数没做打印

**Comment by LiuNull** [comment]
搞定，非常感谢！

**Comment by yorkane** [comment]
为什么我留空了没有用
