### ISSUE TITLE
🙋 钉钉回答的和其他平台网页端的回答不一样

### ISSUE THREAD

**Issue by Raytow** [eryajf/chatgpt-dingtalk#84]
## 问题反馈

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/chatgpt-dingtalk/issues)，请勿重复提交issue。

**重要：提交问题时，请务必带上输出日志，以及个人排查的成果。**
这是钉钉的回复:
问:眼睛长了个疙瘩怎么办?
答:如果您长了眼睛的疙瘩，建议您先用温水洗净双手，再用清洁的纱布蘸一些盐水轻轻擦拭疙瘩，不要揉搓或挤压。如果疙瘩长时间不消退或出现其他异常症状，建议您到医院就诊或咨询专业医生。同时，要注意保持眼部卫生，避免使用不干净的手或物品接触眼睛。
下面是其他网页端turbo3.5的回复:
如果你的眼睛长了一个疙瘩，建议你立即咨询专业医生或眼科医生。他们可以对你的状况进行评估并给出最佳治疗建议。

在等待看医生的过程中，避免揉搓或挤压眼睛，以免加重症状。如果有不适感，可以用温水湿敷来缓解疼痛和肿胀。

请注意，眼睛是非常脆弱和重要的器官，对于任何视觉问题都应该及时咨询医生的意见，以防止严重的后果。

**Comment by eryajf** [comment]
这很正常，不必重复提这个问题了，可以看看这里了解一下：https://github.com/PlexPt/awesome-chatgpt-prompts-zh
