### ISSUE TITLE
模型指定与实际调用不一致

### ISSUE THREAD

**Issue by LiuNull** [eryajf/chatgpt-dingtalk#85]
0.1.6版本，在配置文件中，指定模型为gpt-3.5-turbo，但是实际调用为gpt-3.5-turbo-0301，请问是什么原因呢？

![image](https://user-images.githubusercontent.com/19554995/224218744-76e4546e-e8ac-4ac5-8492-2e1f3ea37492.png)

![image](https://user-images.githubusercontent.com/19554995/224218865-579b14b4-9674-498b-9b6b-f690c611e44d.png)

**Comment by Space2048** [comment]
我也有这个问题诶

**Comment by eryajf** [comment]
关于这个，我找不到答案😂
