### ISSUE TITLE
🙋 问题交流

### ISSUE THREAD

**Issue by Facemax** [eryajf/chatgpt-dingtalk#86]
## 问题反馈
你好，eryajf！
请问下为什么我在playground使用Model->chat->gpt-3.5-turbo-0301和使用钉钉调用，同样的问题，前者更为详细，是什么参数在影响呢？
![1678430541562](https://user-images.githubusercontent.com/19884263/224242779-23e31799-0190-4a45-af25-771ac38c9620.jpg)

如果是参数影响，我是通过docker布置的，能直接修改image 吗？想知道如何做？
谢谢你的及时回复，祝你有美好的一天

**Comment by eryajf** [comment]
比如可以通过添加一些修饰词进行调教：

<img width="802" alt="image" src="https://user-images.githubusercontent.com/33259379/224297340-77aacb1d-cea7-4979-835d-486e1523a7c4.png">
