### ISSUE TITLE
源码构建go可执行程序后执行报错: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by baby9** [eryajf/chatgpt-dingtalk#88]
完整报错信息如下:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/eryajf/chatgpt-dingtalk/public.GetBalance()
	/app/public/gpt.go:47 +0x6c9
github.com/eryajf/chatgpt-dingtalk/public.InitSvc()
	/app/public/public.go:16 +0xca
main.init.0()
	/app/main.go:17 +0x17

**Comment by eryajf** [comment]
可以确认下是不是api_key被禁用了

**Comment by baby9** [comment]
确实是API被禁用了
