### ISSUE TITLE
4.0版本啥时候能上

### ISSUE THREAD

**Issue by MutouLee** [eryajf/chatgpt-dingtalk#89]
看新闻说GPT4.0发布了，PLUS用户可以体验了，咱们这个啥时候更新到4.0 ？

**Comment by eryajf** [comment]
目前我这边没有plus账号，个人白名单也还没开放，不过理论上只要官方开放了，到时候我这边稍微微调一下，就能用上了

**Comment by MutouLee** [comment]
> 目前我这边没有plus账号，个人白名单也还没开放，不过理论上只要官方开放了，到时候我这边稍微微调一下，就能用上了

感谢回复，持续关注中
