### ISSUE TITLE
上下文的逻辑有些怪

### ISSUE THREAD

**Issue by seamusopen** [eryajf/chatgpt-dingtalk#9]
每次都会把上次的提问和回复作为新的问题提交
这是符合预期的吗？

eg:
Q1:你好
A1:你好，很高兴认识你。
Q2:今天天气怎么样

Q2实际发送给openAI的请求是："你好 你好，很高兴认识你。 今天天气怎么样"

**Comment by eryajf** [comment]
就是通过这样一种方式实现的所谓上下文，算是一个伪上下文

**Comment by eryajf** [comment]
我不了解官方有没有提供上下文方面的接口

**Comment by seamusopen** [comment]
这样的话 你测试时可以获取预期的结果吗
我这边完全答非所问了
