### ISSUE TITLE
聊天自动重试的机制发现没了

### ISSUE THREAD

**Issue by MrHadess** [eryajf/chatgpt-dingtalk#91]
https://github.com/eryajf/chatgpt-dingtalk/pull/19 在19这个单子的时候是有相应的重试机制的。但是到了最新版的时候，发现由于新引入的库，相应的重试代码都没了。只剩下余额查询功能是有重试机制的

https://github.com/sashabaranov/go-openai/issues/76 也翻阅作者原来调用的库，也是建议自行实现这个机制的

不知道作者是否能帮忙加上？毕竟挂了代理后发现网络异常的概率是挺大的，现在聊天的时候就会发现，总是会报错

譬如如下这些日志的打印
```
[INFO]2023/03/15 15:54:46 logger.go:21: gpt request error: Post "https://api.openai.com/v1/chat/completions": EOF
[WARNING]2023/03/15 15:54:46 logger.go:33: get gpt result falied: <nil>
```

**Comment by MrHadess** [comment]
现在出现这个错误的次数还是蛮多的 😂

**Comment by sscoo** [comment]
请求 OpenAI 失败了

错误信息:error, EOF

这个问题挺多的
