### ISSUE TITLE
🙋 哭了，闲聊党太多余额瞬间没了，有解决办法么。。

### ISSUE THREAD

**Issue by auvgfw** [eryajf/chatgpt-dingtalk#97]
作者大大您好
我是个编程老师，给同行们开了一个钉钉群，挂上了这个机器人，想着让不敢科学上网的老师们能体验一下chatgpt。。
结果有好多老师水起来没完没了，18刀的账号俩礼拜就聊没了。。
说了也不听，一踢了之又不太合适，平时多多少少还会打些交到。。
请问能不能怎加每人每天最多聊几句的限制，多谢您了
如果能告诉我如何修改也行，本人没用过go，但是对py、php还算熟悉
主要是没在项目里见到数据库的影子，那个go专属的cache又不太了解

**Comment by eryajf** [comment]
这倒是一开始没想到过的一个情况，不过要想添加这个限制，也不算复杂，稍后我来加下

**Comment by eryajf** [comment]
最新版本已支持该功能：https://github.com/eryajf/chatgpt-dingtalk/releases/tag/v0.1.10

有问题再沟通。

**Comment by auvgfw** [comment]
(⊙o⊙)哇 作者大大好腻害
